### ISSUE TITLE
match tracking ala xml unit

### ISSUE THREAD

**Issue by k1w1m8** [lukas-krecan/JsonUnit#100]
Hi Lucas,

I use both json-unit and xml-unit. xmlunit has a very simple MatchTracker API which I find useful to add logging and also to collect statistics.

public interface MatchTracker
Listener for callbacks from a DifferenceEngine comparison that is notified on each and every comparision that resulted in a match.

I was wondering if you would consider adding something similar to JsonUnit? 

That would enable me to extend logging and stats to include the json data of my test app.

**Comment by lukas-krecan** [comment]
Hi, on one hand it would be easy to add. On the other hand, this is exactly the kind of feature that is hard to do right and it's something that would make later changes and refactoring much more challenging. Will think about it but do not hold your breadth.

**Comment by k1w1m8** [comment]
Would it help if I did a pull request?

**Comment by lukas-krecan** [comment]
You can try. There are some tricky situations like IGNORING_ARRAY_ORDER and IGNORING_EXTRA_ARRAY_ITEMS when we have to compare the nodes several times trying to find the match other than that it should be quite straightforward. What I am afraid of are maintenance costs of such feature.

**Comment by k1w1m8** [comment]
OK, you've scared me a bit ;-).

Lets see if I am as motivated as I hope I am.

**Comment by lukas-krecan** [comment]
While we still do not have tracking of matches, we have added tracking of differences https://github.com/lukas-krecan/JsonUnit/blob/master/json-unit-core/src/main/java/net/javacrumbs/jsonunit/core/listener/DifferenceListener.java.

**Comment by k1w1m8** [comment]
Very nice.

I guess match tracking cam be considered as an extension of difference listening, it is really just listening to successful comparisons as well as failed comparisons. Now that difference listening is done I would imagine that is the majority of the work.

Please can you re-open this one, as it really was the match tracking I was asking for rather than the difference listening.

**Comment by lukas-krecan** [comment]
Hi, the trouble is that match tracking is much harder to implement and I do not understand the use case.

Let's say I am comparing arrays like this while ignoring array order
`[[1,2,3],[2,3,4]] ` vs. ` [[4,2,3],[2,1,4]]`

what should be reported by match tracking? I order to compare arrays like this, the algorithm has to do backtracking and I do not see how to report it.
