### ISSUE TITLE
Better fluent API

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#106]
`public void isObject()` and `public void isString()` should not be void, because having:
`assertThatJson(myJson).isObject().node("nested").isObject()` or `assertThatJson(myJson).isString().isEqualTo("myStr)` is perfectly valid

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Right now I am working on tighter integration with AssertJ library where it might work as in you examples. On the other hand, both isObject() and isString() are superfluousthe examples above. By using `node` or comparing to string you implicitly verify the type of the object. The original purpose of those method was to assert type without making any further assertions.
