### ISSUE TITLE
Add customization for diff output

### ISSUE THREAD

**Issue by viclovsky** [lukas-krecan/JsonUnit#109]
We are able to see such diff with AssertionError `java.lang.AssertionError: JSON documents are different:
Different value found in node "root.igno.red", expected: <1> but was: <2>`
Is it possible add some filter so we are able to customize the output? In this case we will be able to add such custom features as writing output to file or creating an html-file with all ignored paths which we are able to attach to allure-report (https://github.com/allure-framework); or convert diff into unified diff. 
Usually, it is made via filters. For instance, Rest-assured: https://github.com/rest-assured/rest-assured/wiki/Usage#filters

**Comment by viclovsky** [comment]
@lukas-krecan, if you don't mind, I can do it

**Comment by lukas-krecan** [comment]
Ok
