### ISSUE TITLE
Diff message for arrays doesn't have missing/adding elements if IGNORING_ARRAY_ORDER set to false

### ISSUE THREAD

**Issue by viclovsky** [lukas-krecan/JsonUnit#114]
IGNORING_ARRAY_ORDER set to false
I have two arrays: 
"[1, 2]", "[1]"
The diff doesn't have missing/adding elements in error message, but should have
"
JSON documents are different:
Array "" has different length, expected: <1> but was: <2>.
"

See test cases here: 
https://github.com/lukas-krecan/JsonUnit/pull/113/files#diff-1b23aab7241fe7c69ff9c75f028c7db0R131

**Comment by lukas-krecan** [comment]
released as 1.30.0
