### ISSUE TITLE
Possibility to check if object/array is empty

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#116]
Currently we can check if JSON `isObject()` which checks if it's object (empty or not) and `isAbsent()` which checks if particulat node is `""` (but because `isObject()` is void, we can not use it here)
I'd like to check if Object is empty: `{}`.
Can you please provide something like: `isObject().isEmpty()`?
By the way: `isArray().isEmpty()` would be also helpful instead of `isArray().ofLength(0)`

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you use `.isEqualTo("{}")` or `.isEqualTo("[]")`? I do not feel that emptiness check is such common use-case to warrant a special method.

**Comment by eximius313** [comment]
well, I can and I do.
I filled this feature request because "emptiness" of array/object is rather common case in tests

**Comment by bobtiernay-okta** [comment]
Also, how does one say `isNotEmpty()`? That isn't covered  by `isEqualTo`.

**Comment by bobtiernay-okta** [comment]
>  I do not feel that emptiness check is such common use-case to warrant a special method.

Interesting that you assert this then:

https://github.com/lukas-krecan/JsonUnit/blob/d380b07e4946ed8d7a18c0b9dec8f7fc9e38de8c/tests/test-base/src/main/java/net/javacrumbs/jsonunit/test/base/AbstractAssertJTest.java#L689

I do believe there is a lot of value in `isEmpty`, `isNotEmpty` as it is more intent revealing. This is one of the reasons AssertJ provides similar methods for collections:

- https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/EnumerableAssert.html#isNotEmpty()
- https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/EnumerableAssert.html#isEmpty()

Imo, having as many such methods for the common cases helps to keep the test code more readable.

**Comment by lukas-krecan** [comment]
@bobtiernay-okta It's already covered in json-unit-assertj, are you using `net.javacrumbs.jsonunit.fluent` assertions? (I am just checking that In understand your issue)

**Comment by bobtiernay-okta** [comment]
I'm not seeing that in `net.javacrumbs.jsonunit.fluent.JsonFluentAssert` as of version `2.7.0` at least:

![image](https://user-images.githubusercontent.com/25536705/61552711-906c3300-aa26-11e9-8e2e-54409e0963bb.png)

Can you please link me to it?

**Comment by lukas-krecan** [comment]
Sorry for misunderstanding. There are two APIs as described here https://github.com/lukas-krecan/JsonUnit#apis. Fluent assertions, that you are using, do not contain array emptiness check. Newer AssertJ integration does. But yesterday I have committed  array emptiness check to the Fluent assertions so you can expect it in the next release.

**Comment by bobtiernay-okta** [comment]
Ah, my bad! Thanks for the clarification, much appreciated. Thanks for such a great library!
