### ISSUE TITLE
Can not access node with specific characters

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#118]
I have a Json `{"errors":{"days[0].date":["validation.failed"]}}`
As you can see field name is `"days[0].date"`, because it corresponds with HTTP POST params.
I want to check it using `node("errors.days[0].finish").isArray()` but I get `"errors.days[0].finish", expected: <array> but was: <missing>`

**Comment by lukas-krecan** [comment]
hi, you can escape the dot like this `assertThatJson("{\"name.with.dot\": \"value\"}").node("name\\.with\\.dot").isStringEqualTo("value");`

**Comment by eximius313** [comment]
I tried:
```
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days[0].date").isArray();
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days[0]\\.date").isArray();
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days[0]\\\\.date").isArray();
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days\\[0\\]\\.date").isArray();
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days\\\\[0\\\\]\\\\.date").isArray();
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days\\[0\\].date").isArray();
    JsonFluentAssert.assertThatJson("{\"errors\":{\"days[0].date\":[\"validation.failed\"]}}").node("errors.days\\\\[0\\\\].date").isArray();
```
all failed with `java.lang.AssertionError: Different value found in node "errors.days[0]\\.date", expected: <array> but was: <missing>.`
Can you please write correct dotting for this example?

**Comment by lukas-krecan** [comment]
Works on my machine 
https://github.com/lukas-krecan/JsonUnit/commit/26cdffdb1798c6d8ffb6fea3b6f755103d3cf0b8
