### ISSUE TITLE
support number regex

### ISSUE THREAD

**Issue by JFRabbit** [lukas-krecan/JsonUnit#129]
JSON string: {"code":11001}

Could you consider to support a regex like ^11(\d){3}$ to match a number?

Cause in method compareNodes of class Diff, only compare regex when NodeType equal and type is STRING.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I do not think that comparing numbers using regexp is a good idea. Luckily, you can use Custom Matchers to do that https://github.com/lukas-krecan/JsonUnit#custom-matchers
