### ISSUE TITLE
Numbers are not handled correctly

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#131]
Having:
```
final String json = "{\"myNum\": \"1140.53\"}";
```
then these:
```
assertThatJson(json).node("myNum").isEqualTo("1140.53");
assertThatJson(json).node("myNum").hasToString("1140.53");
assertThatJson(json).node("myNum").asString().isEqualTo("1140.53");
```
or this:
```
assertThatJson(json).node("myNum").isNumber().isEqualByComparingTo("1140.53");
```

should pass.
Unfortunatelly - all fail.

(version `2.0.0.RC1`)

**Comment by lukas-krecan** [comment]
Thanks. myNum is not a number, it's a string that accidentally contains number. In other words "1140.53" is not the same as 1140.53. So you have to do 

    assertThatJson(json).node("myNum").isEqualTo("\"1140.53\"")

I will take a look at asString since it fails in an unexpected way.

**Comment by lukas-krecan** [comment]
It's actually an interesting question, how it should behave in this case, if I remember correctly, in older variants of json-unit there is a code that handles such cases. The question is, if we want it here as well. Do we want to differentiate between "1" and 1 or not.

**Comment by lukas-krecan** [comment]
You can use isString

**Comment by lukas-krecan** [comment]
asString fixed in 2.0.0.RC2

**Comment by eximius313** [comment]
this: `assertThatJson(json).node("myNum").hasToString("1140.53");` still returns:
```
[error] Test project.Test failed: java.lang.AssertionError:
[error] Expecting actual's toString() to return:
[error]   <"1140.53">
[error] but was:
[error]   <"1140.53">, took 1.36 sec
```
but `asString` and `isString` work.

**Comment by lukas-krecan** [comment]
There is actually a clash of two reasonable expectations
1) `parse(json).toString()` should return a JSON which is equivalent to the original. For example `parse("{\"a\": 1}").toString()` should return '{"a":1}'. That leads to `parse("\"aaaaa\"").toString()` should return '"aaaaa"' (standalone String in JSON has to be in double quotes)
2) The other expectation is, that "aaaaa".toString() should return 'aaaaa' without double quotes

It boils down to the question, if taking a String value from JSON makes it a JSON string or Java String.

**Comment by eximius313** [comment]
I think it's `toString` not `prettyPrint` therefore I'd go with `2` ("Java String"), and expect that:
`parse("{\"a\": 1}").node("a").hasToString("1")`
and
`parse("{\"a\": "1"}").node("a").hasToString("1")`

**Comment by lukas-krecan** [comment]
Duplicate  of #162

**Comment by eximius313** [comment]
so with `value` approach, this `parse("{\"a\": "1"}").node("a").hasToString("1")` will become `parse("{\"a\": "1"}").node("a").hasToString(value("1"))`?
