### ISSUE TITLE
please introduce asNumber (as counterpart to asString)

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#138]
`asNumber` could be counterpart to `asString` and treat `{"foo": "21.32"}` as BigDecimal

**Comment by lukas-krecan** [comment]
There already is isNumber, isBoolean, isArray ... asString has been inherited form AssertJ so I had to fix it but I do not see any advantage of adding asXXXX synonyms

**Comment by eximius313** [comment]
well, the reason is simple: If I have "21.32" I can not use `isNumber`, because you throw:
```
failed: java.lang.AssertionError: Node "foo" has invalid type, expected: <number> but was: <"21.32">., took 3.195 sec
```
and I want to use comparisons like "isLessThan". I can not do that on String...

**Comment by lukas-krecan** [comment]
As I have written in the previous comment, there already is `isNumber`

**Comment by lukas-krecan** [comment]
Ah, I see, you want something that changes type of your string to a number. Can't you use `extracting` from AssertJ

**Comment by eximius313** [comment]
yes! I want to "cast" my "string-formatted number" (most often the result of `@JsonFormat(shape=Shape.String)` ) to real number :)

Extracting works in different way (more like getter)

**Comment by eximius313** [comment]
@lukas-krecan Is my explanation worth reopening this issue?

**Comment by lukas-krecan** [comment]
Introduced in 2.0.0RC3

**Comment by eximius313** [comment]
works as expected! Thanks ;)
