### ISSUE TITLE
Considering throwing org.opentest4j.MultipleFailuresError

### ISSUE THREAD

**Issue by filiphr** [lukas-krecan/JsonUnit#146]
Before I start going into the feature request. I have to say thank you for this awesome library. I found out about it few days ago and it has helped me tremendously in writing our REST tests.

Now with the feature request. Have you considered using [`MultipleFailureError`](https://github.com/ota4j-team/opentest4j/blob/master/src/main/java/org/opentest4j/MultipleFailuresError.java) from opentest4j? It comes as an initiative from the JUnit 5 team and it already has support by the different IDEs. JUnit 5 uses that for their `Assertions.assertAll`. 

Currently the IDE (IntelliJ) does some weird diff comparison. I think that if you report multiple errors (which is already the case considering the fact that the json-unit `Diff` has multiple errors) the diff comparison created by the IDE (IntelliJ) would be better.

Note: When I say IntelliJ it is because I am using that, not sure how this would look like in Eclipse

**Comment by lukas-krecan** [comment]
Hi, thanks for the suggestion, will take a look at it

**Comment by lukas-krecan** [comment]
The change is quite easy https://github.com/lukas-krecan/JsonUnit/pull/147 but IntelliJ still does the same comparison. Do you have any information if opentest4j already is supported IntelliJ?

**Comment by lukas-krecan** [comment]
I found it, it will be supported in 2019.1. https://youtrack.jetbrains.com/issue/IDEA-179482

**Comment by filiphr** [comment]
Thanks for looking into this. If you are in a JUnit 5 test suite this is going to work. The linked issue in IntelliJ is actually for a global support (I created it 😄).

I will try your PR in my project and will let you know how it looks like.

**Comment by lukas-krecan** [comment]
Released as 2.2.0
