### ISSUE TITLE
AssertJ inPath().isAbsent() is broken

### ISSUE THREAD

**Issue by jrehwaldt** [lukas-krecan/JsonUnit#148]
AssertJ's variant of `assertThatJson("{}").inPath("abc").isAbsent()` is broken. Due to eager evaluation of `inPath` a `com.jayway.jsonpath.PathNotFoundException: No results for path: $['abc']` is thrown.

**Comment by lukas-krecan** [comment]
Thanks a lot, good catch, will fix

**Comment by lukas-krecan** [comment]
Released as 2.0.3
