### ISSUE TITLE
Move configuration methods to ConfigurableJsonAssert

### ISSUE THREAD

**Issue by filiphr** [lukas-krecan/JsonUnit#159]
The `Configuration` currently has the following methods:

* `public Configuration withTolerance(BigDecimal)`
* `public Configuration withTolerance(double)`
* `public Configuration when(Option, Option...)`
* `public Configuration withOptions(Option, Option...)`
* `public Configuration withOptions(Options)`
* `public Configuration whenIgnoringPaths(String...)` 
* `public Configuration withIgnorePlaceholder(String)`
* `public Configuration withMatcher(String)`
* `public Configuration withDifferenceListener(DifferenceListener)`

However, the `ConfigurableJsonAssert` only has the `when(Option, Option...)` and of course the `withConfiguration`. If those methods were passed to the `ConfigurableAssert` it would make it a bit easier to discover them and use them.

**Comment by lukas-krecan** [comment]
Thanks, I was trying to get away with only specifying `withConfiguration` method, but you are right.

**Comment by filiphr** [comment]
😀, yes having the `withConfiguration` helps. If you want I can try and make a PR for you to review

**Comment by lukas-krecan** [comment]
No need, there already is this commit https://github.com/lukas-krecan/JsonUnit/commit/28826ccf01b3005a704c7910230cf771929af8a1. Thanks
