### ISSUE TITLE
AssertJ .withFailMessage(...) is ignored

### ISSUE THREAD

**Issue by olasundell** [lukas-krecan/JsonUnit#160]
Hi, and thanks for a great library!

I've done this:

`JsonAssertions.assertThatJson(EntityUtils.toString(ngJson.entity))
        .withConfiguration { c -> c.whenIgnoringPaths("links.related.linkrel[*].options.url",
                "links.related.topcontentrel[*].options.url",
                "response.url",
                "links.related.videoklipp[*].options.url",
                "links.related.linkdestinationrel[*].options.url") }
        .withFailMessage("$id failed")
        .isEqualTo(EntityUtils.toString(oldJson.entity))`

and I just can't get the `withFailMessage(...)` to stick. Is this WAD?

**Comment by lukas-krecan** [comment]
It's not implemented (yet). I assume that you expect it to override complete error message, is correct? If so, I will implement it in next few days.

**Comment by olasundell** [comment]
Yes, and thank you. I'll eagerly await the next release.

**Comment by lukas-krecan** [comment]
Released as 2.4.0
