### ISSUE TITLE
[Feature] Plese add "asMap" method

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#161]
Simmilar to `asList()`, `asNumber()` and `asString()` new method `asMap()` is very important, to cast assertion to `AbstractMapAssert`.

Could you please add it?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. What would be the difference between `asMap()` and `isObject()`? Is it about the name or is there some other difference as well?

**Comment by eximius313** [comment]
`isObject()` indeed returns `MapAssert`. 
I have to admit that I didn't event thought that `isObject` could do such thing.
We can close this for now, but when any other person make such mistake, then it could be worth to reconsider the naming.
