### ISSUE TITLE
[BUG] inPath is not working correctly

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#162]
None of this tests passes:
```
    assertThatJson("{\"fields\": [{ \"id\": \"test\", \"value\": \"true\" }]}")
      .inPath("$.fields[?(@.id==\"test\")].value")
      .isArray()
      .containsExactly("true");
```
```
    assertThatJson("{\"fields\": [{ \"id\": \"test\", \"value\": \"true\" }]}")
      .inPath("$.fields[?(@.id==\"test\")].value")
      .isArray()
      .containsExactly(true);
```
```
    final Map<String, Integer> map = new HashMap<>();
    map.put("FOO", 4);
    map.put("BAR", 3);
    assertThatJson("{\"fields\": [{ \"id\": \"test\", \"value\": \"{FOO=4, BAR=3}\" }]}")
      .inPath("$.fields[?(@.id==\"test\")].value")
      .isArray()
      .containsExactly(map.toString());
```
```
    final Map<String, Integer> map = new HashMap<>();
    map.put("FOO", 4);
    map.put("BAR", 3);
    assertThatJson("{\"fields\": [{ \"id\": \"test\", \"value\": \"{FOO:4, BAR:3}\" }]}")
      .inPath("$.fields[?(@.id==\"test\")].value")
      .isArray()
      .containsExactly(map);
```

**Comment by lukas-krecan** [comment]
Hi, the first example is indeed a bug, but quite hard one to fix. I will have to do some refactoring to fix it. 

The other two would expect the library to guess that the string content in "value" field is an (invalid) JSON, leniently parse it and then compare it. Please check https://github.com/lukas-krecan/JsonUnit/issues/155 for possible solution.

**Comment by eximius313** [comment]
what about the last one? `{FOO:4, BAR:3}` is valid JsonObject (map as we already saw in https://github.com/lukas-krecan/JsonUnit/issues/161)

**Comment by lukas-krecan** [comment]
I see, 3rd should work. It's the same bug as the first one

**Comment by lukas-krecan** [comment]
The trouble is not cleanly defined behavior of `.containsExactly("someString")` method. (similar to #131). Currently it parses "someString" as JSON which converts `.containsExactly("true")` to boolean `true`. Since I do not want to break all tests that people have written with this assumption, I had to introduce `value()` method which declares that the string should not get parsed (I am not sure about the name `value`). So the test will look like this:

```
       assertThatJson("{\"fields\": [{ \"id\": \"test\", \"value\": \"true\" }]}")
            .inPath("$.fields[?(@.id==\"test\")].value")
            .isArray()
            .containsExactly(value("true"));
```
What do you think?

https://github.com/lukas-krecan/JsonUnit/pull/163/files#diff-b77b022fb6e47e0b0ad18369d030b706R969

**Comment by eximius313** [comment]
we could give it a go and change the behavior in next major version, because currently user ends up in quite confusing `"true" is not "true"` situations :)
If anyone is using this that way, then I'd really like to see their working use case

**Comment by eximius313** [comment]
Ive just tested version `2.4.0` and while indeed it works fine for `map.toString()`, I still need to use `value("true")` instead of `value(true)`. 
Is it expected behavior?

**Comment by lukas-krecan** [comment]
Yes it is

**Comment by eximius313** [comment]
So it only String is accepted, then `value()` should definitely take String as an agrument (or if we stay with Object, then why value can not make `String.valueOf` by itself?)
