### ISSUE TITLE
Johnzon NodeFactory

### ISSUE THREAD

**Issue by elexx** [lukas-krecan/JsonUnit#165]
Hello,

I am using [Apache Johnzon](https://johnzon.apache.org/) in a project as JSON-library, unfortunatly JsonUnit does not support Johnzon out of the box.
I had a quick look at  `net.javacrumbs.jsonunit.core.internal.Converter` - it doesn't seem to be plugable in a way where I just can add my custom NodeFactory.
Are you interested in a PR for a Johnzon-based NodeFactory or maybe even a rewrite of this part of JsonUnit to use a completly modular system (ServiceLoader)?

Regards, Alex

**Comment by lukas-krecan** [comment]
Hi, I will be glad if you provide a NodeFactory for Johnzon. I am reluctant to make it configurable since it would prevent any refactoring. 

19. 2. 2019 14:14, 14:14, Alexander Falb <notifications@github.com> napsal/a:

**Comment by elexx** [comment]
After https://issues.apache.org/jira/browse/JOHNZON-203 got resolved I started working on this. Have a look at https://github.com/elexx/JsonUnit/tree/feature/165-Johnzon_NodeFactory
However Johnzon/JSONP does not support any kind of lenient mode, so a ton of unittests are currently broken. I might have to ship some patches to Johnzon first, before I can further work on the NodeFactory.

**Comment by lukas-krecan** [comment]
Hi, sorry for late response. Lenient parsing is not needed, I think that some other supported parsers do not have it. I have rebased your changes and made some fixes so only few tests are currently failing. I did not have time to check the reason for the failures  https://github.com/lukas-krecan/JsonUnit/pull/175

**Comment by lukas-krecan** [comment]
Hi, I have fixed the tests so the only thing missing is to wait for johnzon 1.1.12 release. The new `toStructure` method is not strictly necessary, we can use `GenericNodeBuilder` as we do for some other libraries. It would also be nice to add support for arrays to `toStructure`, now I have to convert them to lists.

**Comment by elexx** [comment]
I just created a [PR](https://github.com/apache/johnzon/pull/38) to [Johnzon-205](https://issues.apache.org/jira/browse/JOHNZON-205) to add support for arrays, let's see if or when it gets merged.
Regarding the release I'm not sure when this will be. Maybe using the `GenericNodeBuilder` for now would be a safer way to go? What do you think?

**Comment by elexx** [comment]
Looks like we are almost there. I tried to remove the special treatment in `JohnzonNodeFactory#doConvertValue` and found another problem. Johnzon does not support mapping an `Object[]{x}` with `x` being already a converted value to an json-array. It actually converts `x` again and exposes the internals as json content, resulting in something like this `[{"integral":true,"valueType":"NUMBER","value":1}]` instead of `[1]`.
This breaks AbstractAssertJTest#testEqualsToObjectArray.

Just for reference: [Johnzon-206](https://issues.apache.org/jira/browse/JOHNZON-206). Once this is sorted out, I will come back to this PR.

**Comment by lukas-krecan** [comment]
Ok, if you do not need it urgently, I would wait for Johnzon release. If you do need it, we can release a version with GenericNode factory which would have slightly limited support of Johnzon classes (see the failing tests here https://travis-ci.org/lukas-krecan/JsonUnit/builds/514298938) and later release full support. I will leave the decision to you. Thanks a lot

**Comment by elexx** [comment]
I'm fine with waiting for Johnzon :-)

**Comment by lukas-krecan** [comment]
Merged
