### ISSUE TITLE
Ignore node key case sensitivity

### ISSUE THREAD

**Issue by sme81** [lukas-krecan/JsonUnit#171]
Would there be much work in adding the ability to ignore case of node keys between actual and expected JSON messages? 

I have JSON coming back from multiple different sources with the same structure, however the node casing is different between them.

I can see options for ignoring node values casing, but not the nodes key itself 

The following tests should hopefully get this across.

Many thanks 

```
@Test
    void nodeCaseInsensitiveShouldMatch() {
        assertJsonEquals(
                "{\"test\": \"a\"}",
                "{\"Test\": \"a\"}",
                when(IGNORING_NODE_CASE_SENSITIVITY)
        );
    }

@Test
    void nodeCaseInsensitiveValueMismatchShouldFail() {
        try {
            assertJsonEquals(
                    "{\"test\": \"a\"}",
                    "{\"Test\": \"z\"}",
                    when(IGNORING_NODE_CASE_SENSITIVITY)
            );
        } catch (AssertionError e) {
            assertEquals("JSON documents are different:\nDifferent keys found in node \"\", missing: \"test\", extra: \"Test\", expected: <{\"test\":\"a\"}> but was: <{\"Test\":\"z\"}>\n", e.getMessage());
        }
    }
```

**Comment by lukas-krecan** [comment]
Hi, this can be done. The only issue is that processing documents like `{"test": 1, "Test": 2}` will get tricky. Let me think about it.

**Comment by lukas-krecan** [comment]
Hi, I have decides that it does not make sense to add the feature into the product. The functionality you need can be achieved by custom Jackson configuration similar to this https://github.com/lukas-krecan/JsonUnit/pull/174/files
