### ISSUE TITLE
Ignoring Values of all sub fields at a given JSONPath

### ISSUE THREAD

**Issue by fun2sh** [lukas-krecan/JsonUnit#172]
How can I ignore the values of all subfields at a given path? It seems that the only way currently is to go and put "${json-unit.ignore}" for every subfields.

Ex:- My Json string is:

```{
  "items": [
    {
      "parent": {
        "child1": "aaaa",
        "child2": "1111"
      }
    },
    {
      "parent": {
        "child1": "bbbb",
        "child2": "2222"
      }
    },
    {
      "parent": {
        "child1": "cccc",
        "child2": "3333"
      }
    },
    {
      "parent": {
        "child1": "dddd",
        "child2": "4444"
      }
    }
  ]
} 
```

So, I want to ignore the values of path: "items[*].parent.child2" while comparing.

Current way would be to put the place holder for each of the array items

**Comment by lukas-krecan** [comment]
Hi, did you try this https://github.com/lukas-krecan/JsonUnit/blob/master/README.md#ignoring-paths?

**Comment by fun2sh** [comment]
> Hi, did you try this https://github.com/lukas-krecan/JsonUnit/blob/master/README.md#ignoring-paths?

That would ignore the path entirely right? I want to check that those sub fields exists but dont want to check for their values

**Comment by lukas-krecan** [comment]
In this case, you can use JsonPath
