### ISSUE TITLE
Enable Options to be applied to only portions of a comparison

### ISSUE THREAD

**Issue by galactoise** [lukas-krecan/JsonUnit#178]
We regularly use JsonUnit to do contract-style testing of very large API responses, and one of the issues we are facing is that the services we're testing do not necessarily use the same strategy for how sibling objects should be returned. Taking array ordering as an example, we often have cases where a service is serializing both a set (unordered) and a list (ordered) as fields in the same response, so we end up with the following situation:

```
String expected = "{\"foo\":[\"firstItem\",\"secondItem\"],\"bar\":[\"someEntry\",\"anotherEntry\"]}";

//This should pass, of course
assertJsonEquals(expected,"{\"foo\":[\"firstItem\",\"secondItem\"],\"bar\":[\"someEntry\",\"anotherEntry\"]}");

//We also want this to pass - by default it doesn't
assertJsonEquals(expected,"{\"foo\":[\"firstItem\",\"secondItem\"],\"bar\":[\"anotherEntry\",\"someEntry\"]}");

//We do not want this to pass - by default it doesn't
assertJsonEquals(expected,"{\"foo\":[\"secondItem\",\"firstItem\"],\"bar\":[\"someEntry\",\"anotherEntry\"]}");

//We can solve the second assertion's failure by doing this:
assertJsonEquals(expected,"{\"foo\":[\"firstItem\",\"secondItem\"],\"bar\":[\"anotherEntry\",\"someEntry\"]}", when(IGNORING_ARRAY_ORDER));

//But now that causes the following case to pass when we don't want it to
assertJsonEquals(expected,"{\"foo\":[\"secondItem\",\"firstItem\"],\"bar\":[\"anotherEntry\",\"someEntry\"]}", when(IGNORING_ARRAY_ORDER));
```

We also run into similar problems with IGNORING_EXTRA_ARRAY_ITEMS, etc.

It would be nice if we could specify at a higher level of granularity which Options to use for different parts of the comparison. Specifically, the `.whenIgnoringPaths` pattern is one that might be a good fit for granular Options, something like `.whenUsingOptionsForPath(String path, Option option...)`

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. You can use multiple `assertJsonPartEquals()` method calls with different options. Implementing `.whenUsingOptionsForPath` would complicate the API and the implementation too much, so I am afraid, I will not do it.
