### ISSUE TITLE
Feature Request: match node with any Matcher

### ISSUE THREAD

**Issue by mkq** [lukas-krecan/JsonUnit#18]
Could you please add support for applying generic Matchers to JSON nodes? For example, make this test work:

    import static net.javacrumbs.jsonunit.fluent.JsonFluentAssert.assertThatJson;
    import static org.hamcrest.Matchers.allOf;
    import static org.hamcrest.Matchers.greaterThanOrEqualTo;
    import static org.hamcrest.Matchers.lessThan;
    import static org.hamcrest.core.IsCollectionContaining.hasItem;
    import static org.junit.Assert.assertThat;
    
    import java.util.Arrays;
    import org.junit.Before;
    import org.junit.Test;
    
    public class JsonFluentFeatureRequest {
    	private String json;
    
    	@Before
    	public void init() {
    		json = "{ 'num': 40, 'messages': [ 'hello', 'world' ] }".replace('\'', '"');
    	}
    	
    	/** The matchers used in the other tests, without JsonUnit. */
    	@Test
    	public void testBasicMatchers() {
    		assertThat(40, allOf(greaterThanOrEqualTo(20), lessThan(100)));
    		assertThat(Arrays.asList("hello", "world"), hasItem("world"));
    	}
    
    	@Test
    	public void testNodeMatchesRegex() {
    		assertThatJson(json).node("messages").matches(hasItem("world"));
    	}
    	
    	@Test
    	public void testNodeMatchesIntegerRange() {
    		assertThatJson(json).node("num").matches(allOf(greaterThanOrEqualTo(20), lessThan(100)));
    	}
    }

Thanks!

**Comment by lukas-krecan** [comment]
Thanks for your input. I will think about it. I would have done it long time ago, but it's tricky regarding types. "messages" may be mixed array (objects, mixed together with strings and ints for example).

**Comment by mkq** [comment]
Thanks for your feedback.

I think some things are better left unsafe (see `java.util.Map#get(Object)`, not `get(K)`). Would it suffice to have a new method `Node.getValue()` (which returns String, Long, Map etc depending on node type, like `org.codehaus.jackson.map.ObjectMapper.readValue(..., Object.class)`) and some static helper methods to create `Matcher<Node>`? Maybe the check from `testNodeMatchesIntegerRange` could be

	assertThatJson(json).node("num").matches(
		NodeMatchers.numberNode(allOf(greaterThanOrEqualTo(20), lessThan(100))));

with class `NodeMatchers` being

	public class NodeMatchers {
		private NodeMatchers() {
		}
	
		public static Matcher<Node> numberNode(Matcher<?> matcher) {
			return new DelegatingNodeMatcher(NodeType.NUMBER, matcher);
		}
	
		public static Matcher<Node> arrayNode(Matcher<?> matcher) {
			return new DelegatingNodeMatcher(NodeType.ARRAY, matcher);
		}
	
		// ... TODO other node types
	
		static class DelegatingNodeMatcher extends BaseMatcher<Node> {
			private final NodeType nodeType;
			private final Matcher<?> matcher;
	
			public DelegatingNodeMatcher(NodeType nodeType, Matcher<?> matcher) {
				this.nodeType = nodeType;
				this.matcher = matcher;
			}
	
			public Matcher<?> getMatcher() {
				return matcher;
			}
	
			public boolean matches(Object item) {
				Node node = (Node) item;
				boolean matches = node.getNodeType() == nodeType && getMatcher().matches(node.getValue());
				if (!matches) {
					Description description = new StringDescription();
					describeTo(description);
					throw new AssertionError("[" + description + "]");
				}
				return true;
			}
	
			public void describeTo(Description description) {
				description.appendText("node matches ").appendDescriptionOf(matcher);
			}
		}
	}

**Comment by lukas-krecan** [comment]
Thanks, I think I have figured out how to do it. Can you please check this commit https://github.com/lukas-krecan/JsonUnit/pull/19/files#diff-87f58159512bd16e388356e87329055d The main open question is what to do with numbers. JSON number can be of arbitrary length and precision  so it's ideally represented by BigDecimal. Unfortunatelly BigDecimals are quite ugly in test. Nevertheless it feels much better then returning int/long/float/duble/BigInteger/BigDecimal depending on the value.

**Comment by mkq** [comment]
That looks great. Except one thing - `NodeType.OBJECT.getValue()` returns Node which is documented as internal. So AFAIU there is no clean way for the user to match object nodes. Could it return a Map (of Maps, Lists, BigDecimals, Strings, etc)?

(Javadoc typo in JsonFluentAssert: "Matches **th** node using Hamcrest matcher.")

**Comment by lukas-krecan** [comment]
Thanks, released as 1.6.0. Enjoy.

**Comment by mkq** [comment]
Excellent support! Thank you very much.
