### ISSUE TITLE
Support whitelist of json paths to check

### ISSUE THREAD

**Issue by shollander** [lukas-krecan/JsonUnit#180]
JsonUnit currently provides support for ignoring paths. This is a very useful feature. However, sometimes it is preferable to be able to the the opposite, i.e. list only the paths that should be compared. It would be great if JsonUnit would support that as well.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Have you considered using IGNORING_EXTRA_FIELDS and specifying only the interesting part of the JSON in the expected value?

**Comment by shollander** [comment]
I somehow missed that option, sorry about that.
