### ISSUE TITLE
When multiple differences are found, AssertionErrors are missing detail

### ISSUE THREAD

**Issue by hannsl** [lukas-krecan/JsonUnit#181]
When multiple differences are found, the individual assertion errors are reported as:

Different value found in node "%s", expected: <%s> but was: <%s>.

This seems to be due to the following line of code in JsonDifference:

    AssertionFailedError getError() {
        return new AssertionFailedError(message, expected.getValue(), actual.getValue());
    }

**Comment by lukas-krecan** [comment]
Hi, thanks a lot for reporting. Will fix it.

**Comment by lukas-krecan** [comment]
Released as 2.6.2
