### ISSUE TITLE
Issue with precision, using BigDecimal

### ISSUE THREAD

**Issue by noncuro** [lukas-krecan/JsonUnit#186]
I think there might be a bug in comparing BigDecimal. I'm running the following assertion:
```
assertThatJson("{\"foo\":7500.00}").node("foo").isEqualTo(BigDecimal("7500.00"))
```
and getting 
```
net.javacrumbs.jsonunit.core.internal.JsonDifference: JSON documents are different:
Different value found in node "foo", 
Expected :7500.00
Actual   :7500.0
```

Any idea why this might be? Am I doing something wrong?

**Comment by lukas-krecan** [comment]
Sorry, I have not read your issue carefully enough (I am on vacation). Will take a look at it, in the meantime please set comparison tolerance.

**Comment by lukas-krecan** [comment]
Hi, please read the documentation

**Comment by lukas-krecan** [comment]
Hi, it's actually an issue with Jackson. String `"{\"foo\":7500.00}"` is parsed by Jackson and the number is converted to double. The best way is to use this 

```
assertThatJson("{\"foo\":7500.00}").node("foo").isNumber().isEqualByComparingTo("7500.00");
```

If you need to compare exact number, you can try to parse the string manually like this ()

```
        ObjectMapper mapper = new ObjectMapper();
        mapper.enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS);

        assertThatJson(mapper.readTree("{\"foo\":7500.00}")).node("foo").isEqualTo(new BigDecimal("7500.00"));
```
