### ISSUE TITLE
Docs: Example of using inPath and whenIgnoringPaths with Hamcrest-style matchers

### ISSUE THREAD

**Issue by mikeb-celtx** [lukas-krecan/JsonUnit#192]
I'm trying to match two mostly-identical structures as follows:

```
assertThat(json1, jsonEquals(json2.toString())
            .when(Option.TREATING_NULL_AS_ABSENT)
            .whenIgnoringPaths("$..ignoredField"));
```
However it's not clear how to do this with the current API

I've tried several variations using `inPath` to accomplish the above, but none seem to actually do the trick. I imagine AssertJ is the primary target here, but if possible it would be massively helpful to see an example in the `whenIgnoringPaths` section of the docs that actually demonstrates combining filters with `inPath`

**Comment by lukas-krecan** [comment]
Sorry, I do not understand what are you trying to achieve. Are you trying to use json-path in whenIgnoringPaths? If so, the library does not support this (and I admit, the documentation is not clear in this regard).

**Comment by francogu** [comment]
Hello, Could you be more precise regarding your comment:

> Are you trying to use json-path in whenIgnoringPaths? If so, the library does not support this

The docmentation states:

> Please note, that if you use JsonPath, you should start the path to be ignored by $ Also note that whenIgnoringPaths method supports full JsonPath syntax only in AssertJ API, all the other flavors support only exact path or array index placeholder as described above.

When using  json-unit-assertj (v2.14.0) ` @Test
    public void testAssertJsonUnit() {
        assertThatJson("{\"fields\":[{\"key\":1, \"name\":\"AA\"},{\"key\":2, \"name\":\"AB\"},{\"key\":3, \"name\":\"AC\"}]}")
             .whenIgnoringPaths("fields[*].key")
                .isEqualTo( "{\"fields\":[{\"key\":2, \"name\":\"AA\"},{\"key\":2, \"name\":\"AB\"},{\"key\":3, \"name\":\"AC\"}]}");
    }`
it works but fail with full JsonPath syntax like 
`  @Test
    public void testAssertJsonUnit() {
        assertThatJson("{\"fields\":[{\"key\":1, \"name\":\"AA\"},{\"key\":2, \"name\":\"AB\"},{\"key\":3, \"name\":\"AC\"}]}")
             .whenIgnoringPaths("fields[?(@.name=='AA')].key")
                .isEqualTo( "{\"fields\":[{\"key\":2, \"name\":\"AA\"},{\"key\":2, \"name\":\"AB\"},{\"key\":3, \"name\":\"AC\"}]}");
    }`

**Comment by lukas-krecan** [comment]
@francogu Hi, it seems you have missed the part `you should start the path to be ignored by $` This test passes https://github.com/lukas-krecan/JsonUnit/commit/26c392fbfe52e9bdebc7e6fa372774581f8927eb I will try to clarify the documentation
