### ISSUE TITLE
json-unit must have a dependency on hamcrest-core

### ISSUE THREAD

**Issue by anilkumarmyla** [lukas-krecan/JsonUnit#193]
This is described in detail at https://github.com/sbt/sbt/issues/4968 and https://github.com/coursier/coursier/issues/1336

1. Describe which variant of the API are you using (AssertJ, Hamcrest, ...)
Hamcrest 

2. Create a small reproducible example and paste it the the bug report.
Ref https://github.com/sbt/sbt/issues/4968

3. Describe expected behavior
Including json-unit should bring in hamcrest-core dependency

**Comment by lukas-krecan** [comment]
Hi, thanks. The dependency it optional intentionally. People that do not want to use Hamcrest, do not need to have it in the classpath. People that do want to use it are supposed to add the dependency explicitly. Moreover, with Hamcrest 2 the situation will get even more messy, since they have changed their group ID.

Since I am not familiar with SBT, I did not actually get what exactly is the problem in SBT. Could you please explain?

**Comment by anilkumarmyla** [comment]
@lukas-krecan The problem in sbt is that anyone including
```
"net.javacrumbs.json-unit"   % "json-unit"       % "2.8.0" % Test,
```
as a test scoped dependency also need to include hamcrest as test scoped dependency (starting with sbt 1.3.0 where its dependency management changed from apache ivy to coursier)
```
  "org.hamcrest"               % "hamcrest"        % "1.3" % Test,
```

While we can argue that hamcrest is supposed to an optional dependency it feels like it is not, based on following deductions
1 `json-unit` has a non-optional dependency on `json-unit-core`
2 `json-unit-core` has a non-optional dependency on `hamcrest-core`
1 & 2 => 3 `json-unit` has a non-optional dependency on `hamcrest-core`

4 `json-unit` depends on `json-unit-parent`
5 `json-unit-parent` has optional dependency on `hamcrest-core`
4 & 5 => 6 `json-unit` has an optional dependency on `hamcrest-core`

3 & 6 => `json-unit` has a non-optional dependency on `hamcrest-core`

> People that do not want to use Hamcrest, do not need to have it in the classpath.

Point 2 above contracts this statement, should `json-unit-core` have an optional dependency on `hamcrest-core` ?

**Comment by lukas-krecan** [comment]
2 and 5 are not true. json-unit-parent specifies Hamcrest only in `dependencyManagement` section which basically defines default values for child contexts. Therefore `json-unit-core` has only optional dependency and `jsoun-unit-parent` none.

**Comment by anilkumarmyla** [comment]
@lukas-krecan thanks for the explanation, I need to go back to learn maven dependency management again 🙈 

Last question, how come there is code that references hamcrest in json-unit-core ex: https://github.com/lukas-krecan/JsonUnit/blob/master/json-unit-core/src/main/java/net/javacrumbs/jsonunit/core/Matchers.java#L18 and dependency is still optional? How does this work at runtime?

**Comment by lukas-krecan** [comment]
You are right. It seems, it's me who should learn dependency management. Event thought the library is marked as 'optional', Maven adds it to dependencies anyway and if I explicitly remove it, the library does not work. So I will mark it as not optional. Thanks for your patience.

**Comment by lukas-krecan** [comment]
Released as 2.8.1

**Comment by anilkumarmyla** [comment]
thanks @lukas-krecan

**Comment by alexarchambault** [comment]
> Event thought the library is marked as 'optional', Maven adds it to dependencies anyway 

@lukas-krecan Note that this is likely [a Maven bug](https://issues.apache.org/jira/browse/MNG-5227), discussed in [this StackOverflow question](https://stackoverflow.com/questions/23611254/is-the-tag-optional-valid-in-dependencymanagement-element).
