### ISSUE TITLE
Hamcrest-Style Array Tests

### ISSUE THREAD

**Issue by DaGeRe** [lukas-krecan/JsonUnit#20]
Is it possible to use Hamcrest-Style tests for testing an array?

While things like

```
JsonFluentAssert.assertThatJson(runningJobs).isArray().ofLength(2);
```

work fine, I can't find a way to do things like this with hamcrest-style matchers.

And is there any way to test weather an array contains a certain node?

For example, if I've got the JSON *[{\"a\": 7},8]*, can I make something like:
```
JsonFluentAssert.assertThatJson(runningJobs).node("{\"a\": 7}").isPresent();
```

to test weather the node is present in an Array?

**Comment by lukas-krecan** [comment]
Hi,
  if you use Hamcrest, you can do something like this 

    assertThatJson("[{\"a\": 7},8]").matches(hasItem(jsonEquals("{\"a\": 7}")));

I hope it helps
