### ISSUE TITLE
Registering a Representation through a file named 'org.assertj.core.presentation.Representation' in the META-INF/services directory is deprecated

### ISSUE THREAD

**Issue by relgames** [lukas-krecan/JsonUnit#200]
Latest assertj (3.13.2) shows this on startup:
```
Although it still works, registering a Representation through a file named 'org.assertj.core.presentation.Representation' in the META-INF/services directory is deprecated.
The proper way of providing a Representation is to register a Configuration as described in the documentation (a Configuration allowing to provide a Representation and other AssertJ configuration elements)
```
It is because of this file https://github.com/lukas-krecan/JsonUnit/blob/08a361daeebbe5dcc50f58cdf426649528cc4ea6/json-unit-assertj/src/main/resources/META-INF/services/org.assertj.core.presentation.Representation

Such error message had been added in v3.13.0 https://github.com/joel-costigliola/assertj-core/issues/1361

**Comment by lukas-krecan** [comment]
Fixed in 2.9.0
