### ISSUE TITLE
Make withFailMessage prepend the custom message to the original one

### ISSUE THREAD

**Issue by npoirey** [lukas-krecan/JsonUnit#207]
**Is your feature request related to a problem? Please describe.**
On our project we often have complex json that we want to compare during unit tests. Using withFailMessage allows us to add functionnal indications for the failure, but then we don't have the original failure reason.
As we also have to ignore some fields, it can be tedious to find the reason a test is failing and we sometime have to remove the "withFailMessage" just to see why the comparison is failing (like we forgot to ignore a varying field)

**Describe the solution you'd like**
Either make withFailMessage print the custom message like now, but also the original failure message, or offer another method that does this.

**Comment by lukas-krecan** [comment]
Thanks, sounds reasonable

**Comment by lukas-krecan** [comment]
I have checked the code and you can use `describedAs`
