### ISSUE TITLE
Does not compare object array correctly

### ISSUE THREAD

**Issue by yarafed** [lukas-krecan/JsonUnit#208]
JsonUnit should not show changed objects as separate extra and missing objects, because they have income fields with the same value. I use option IGNORING_ARRAY_ORDER.

For example:

```
String actual = "[{ \"id\": \"12\", \"name\": \"Sign\"},{ \"id\": \"56\", \"name\": \"Jor\"},{ \"id\": \"22\", \"name\": \"Kol\"}]";
String expected = "[{ \"id\": \"56\", \"name\": \"Feg\"},{ \"id\": \"12\", \"name\": \"Sign\"},{ \"id\": \"17\", \"name\": \"Kol\"}]";
assertJsonEquals(actual,expected, when(Option.IGNORING_ARRAY_ORDER));
```
Should show that object name with id '17' was changed from Jor to Kol. However, it shows like extra and missing elements.
<img width="298" alt="Screen Shot 2019-10-17 at 11 20 35 PM" src="https://user-images.githubusercontent.com/7060626/67044562-2eaa8a80-f135-11e9-88bd-7296511d7ab3.png">
<img width="1297" alt="Screen Shot 2019-10-17 at 11 23 14 PM" src="https://user-images.githubusercontent.com/7060626/67044564-2eaa8a80-f135-11e9-99e6-8e2fc6684847.png">

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. For a human it is obvious, you see the same `id` so you know that the objects are supposed to be the same. For the computer the `id` field is just a normal field. 

Imagine the following comparison (basically it's the same as the one you provided)
```
String actual = "[{ \"firstName\": \"John\", \"name\": \"Sign\"},{ \"firstName\": \"Bill\", \"name\": \"Jor\"},{ \"id\": \"22\", \"name\": \"Kol\"}]";
String expected = "[{ \"firstName\": \"Bill\", \"name\": \"Feg\"},{ \"firstName\": \"John\", \"name\": \"Sign\"},{ \"id\": \"17\", \"name\": \"Kol\"}]";
```

What would be difference now?

Basically we would need to somehow say to the comparison algorithm what is the ID in each object (if any). There is not such feature yet.

**Comment by yarafed** [comment]
@lukas-krecan Thanks for your response!
I am so sorry, that I was not specific. I did not mean just 'id' field.
I mean that maybe _'Diff'_ should compare objects arrays with each other and find if they have common fields. If they have, we should determine the difference between those two objects like 'DIFFERENT', not 'EXTRA'or 'MISSING'.
 It works like that when we have just one difference (for example one object field was changed) between two arrays. In that case, _'Diff'_ determines that as 'DIFFERENT' type. 
![2019-10-22_19h20_21](https://user-images.githubusercontent.com/7060626/67307549-5c128200-f501-11e9-95ad-93fb04808f29.png)

**Comment by lukas-krecan** [comment]
I am afraid that I still do not get it. JsonUnit has special handling for one difference which behaves as you have described. The trouble is that your example contains two differences.

```
"[{ \"id\": \"56\", \"name\": \"Jor\"},{ \"id\": \"22\", \"name\": \"Kol\"}]";
"[{ \"id\": \"17\", \"name\": \"Kol\"},{ \"id\": \"56\", \"name\": \"Feg\"}]";
```
The library would have to somehow guess which pairs belong together. It would have to guess that "Kol" has incorrect `id` and record with `id` 56 has different name. Which might be theoretically possible in this special case, but generic solution would be really complex.

**Comment by yarafed** [comment]
@yarafed You get my idea. For example we have two arrays and two differences:
```
String actual =  "[{ \"id\": \"1\", \"name\": \"S\", \"lastName\": \"W\"},{ \"id\": \"2\", **\"name\": \"J\**", \"lastName\": \"T\"},{ \"id\": \"3\", \"name\": \"K\", \"lastName\": \"Y\"}, {\"id\": \"4\", \"name\": \"U\", \"lastName\": \"W\"}]"
String expected = "[{ \"id\": \"1\", \"name\": \"S\", \"lastName\": \"W\"},{ \"id\": \"2\", **\"name\": \"H\"**, \"lastName\": \"T\"},{ \"id\": \"3\", \"name\": \"K\", \"lastName\": \"Y\"}]"
```
Real result is:
![2019-10-23_16h50_33](https://user-images.githubusercontent.com/7060626/67400077-d3095280-f5b5-11e9-8d07-d6bfd0faceaa.png)
I expect behavior:
![2019-10-23_16h52_45](https://user-images.githubusercontent.com/7060626/67400080-d56bac80-f5b5-11e9-8c49-e391582415c1.png)

So now I understand that is not implemented and would be really complex.
Thank so much for your time!

**Comment by lukas-krecan** [comment]
Ok, just out of curiosity. I am thinking about a feature where you would specify an `id` field and JsonUnit would take it into account when comparing the arrays (compare objects with the same IDs, report missing IDs as missing etc.)

Something like 

```
assertJsonEquals(actual,expected, withId("[*]", "id"));
```

Would it be useful for you?
