### ISSUE TITLE
JSONArray of JSONObjects

### ISSUE THREAD

**Issue by LomaPL** [lukas-krecan/JsonUnit#21]
Hi,

Is there a way to assert JSONArray of three JSONObjects? Server returns the objects in different order each time and IGNORING_ARRAY_ORDER doesn't seem to help here.

Thanks

**Comment by lukas-krecan-gdc** [comment]
Can you please post here a code snippet of your test so I know ho to reproduce it?

**Comment by LomaPL** [comment]
I can only provide a simplified example as the API that returns the response is company internal.

We expect the following JSON:

```json
{
	"response":[
		{
			"empolyees":[
				{
					"firstName":"Joe",
					"lastName":"Doe",
					"dob":"1987-03-21"
				},
				{
					"firstName":"Jason",
					"lastName":"Kowalski",
					"dob":"1986-02-12",
				},
				{
					"firstName":"Kate",
					"lastName":"Smith",
					"dob":"1985-01-11",
				}
			],
			"attributes":null,
			"id":123
		}
```
Server returns employees in different order and now we simply assert whether the expected JSON is equal to actual.

```java
	@Test
	public void testJSON() {

		final String actual = "{\"response\":[{\"attributes\":null,\"empolyees\":[{\"dob\":\"1987-03-21\",\"firstName\":\"Joe\",\"lastName\":\"Doe\"},{\"dob\":\"1986-02-12\",\"firstName\":\"Jason\",\"lastName\":\"Kowalski\"},{\"dob\":\"1985-01-11\",\"firstName\":\"Kate\",\"lastName\":\"Smith\"}],\"id\":123}]}";
		final String expected = "{\"response\":[{\"attributes\":null,\"empolyees\":[{\"dob\":\"1985-01-11\",\"firstName\":\"Kate\",\"lastName\":\"Smith\"},{\"dob\":\"1986-02-12\",\"firstName\":\"Jason\",\"lastName\":\"Kowalski\"},{\"dob\":\"1987-03-21\",\"firstName\":\"Joe\",\"lastName\":\"Doe\"}],\"id\":123}]}";

		assertThatJson(actual).isEqualTo(expected).when(Option.IGNORING_ARRAY_ORDER);
	}
```

**Comment by lukas-krecan** [comment]
If you specify when before the condition it works

    @Test
    public void testArrayShouldMatchRegardlessOfOrder() {

        final String actual = "{\"response\":[{\"attributes\":null,\"empolyees\":[{\"dob\":\"1987-03-21\",\"firstName\":\"Joe\",\"lastName\":\"Doe\"},{\"dob\":\"1986-02-12\",\"firstName\":\"Jason\",\"lastName\":\"Kowalski\"},{\"dob\":\"1985-01-11\",\"firstName\":\"Kate\",\"lastName\":\"Smith\"}],\"id\":123}]}";
        final String expected = "{\"response\":[{\"attributes\":null,\"empolyees\":[{\"dob\":\"1985-01-11\",\"firstName\":\"Kate\",\"lastName\":\"Smith\"},{\"dob\":\"1986-02-12\",\"firstName\":\"Jason\",\"lastName\":\"Kowalski\"},{\"dob\":\"1987-03-21\",\"firstName\":\"Joe\",\"lastName\":\"Doe\"}],\"id\":123}]}";

        assertThatJson(actual).when(Option.IGNORING_ARRAY_ORDER).isEqualTo(expected);
    }

I admit that it's not intuitive and the API should not allow the incorrect combination. If you think about it, in Java isEqualMethod can not know that there will be another method call in the chain so it has to do the comparison at once. I will try to stress it in the documentation.
