### ISSUE TITLE
Incompatibilites between circe, jackson and json-unit

### ISSUE THREAD

**Issue by anilkumarmyla** [lukas-krecan/JsonUnit#217]
json-unit passes a [test](https://github.com/anilkumarmyla/circe-json-failure/blob/master/src/test/scala/example/HelloSpec.scala) when we expect it to fail when using jackson to understand two json objects created by circe (a scala json library). A reproducible test case is included in this repo https://github.com/anilkumarmyla/circe-json-failure

Other libraries like gson or json.org fail the test correctly, but jackson incorrectly passes the test. It might have to do with json-unit integration with jackson

P.S. If not familiar with `sbt`, you can dowload sbt and run `sbt test` in the root of the checked-out repo to see it in action.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. If you send an object to JsonUnit comparison, it tries to convert it to Json model. In case of Jackson it uses `objectMapper.convertValue(json, JsonNode.class)`. Unfortunately, Jackson does not understand circe object and converts them in wrong way (`{"array":false,"null":false,"boolean":false,"string":false,"object":true,"number":false}`).

The solution is to serialize the objects to String and let Jackson parse them again. Or you can try to persuade Jackson to understand circe objects using this mechanism https://github.com/lukas-krecan/JsonUnit#object-mapper-cust.

**Comment by anilkumarmyla** [comment]
Can json-unit error out if its comparing two Object's ("object":true), since everything inherits from Object?

**Comment by lukas-krecan** [comment]
Usually converting object makes sense, like for example [here](https://github.com/lukas-krecan/JsonUnit/blob/master/tests/test-base/src/test/java/net/javacrumbs/jsonunit/test/all/AllJsonAssertTest.java#L136).

**Comment by anilkumarmyla** [comment]
ok, closing since this is known behavior. Thanks for taking a look
