### ISSUE TITLE
Ignore element and child element order

### ISSUE THREAD

**Issue by tutufool** [lukas-krecan/JsonUnit#231]
I'm wondering whether JsonUnit can meeting my requirement:
https://stackoverflow.com/questions/62277192/how-to-compare-2-json-by-ignoring-some-attributes-and-child-element-orders

By roughly go thru document, I found IGNORING_ARRAY_ORDER and IGNORING_VALUES might help in my case.

Yet I'm not sure whether I can get a "difference list" after applied those rules, rather than assertEquals.

**Comment by lukas-krecan** [comment]
Hi, you can take a look at [DifferenceListener](https://github.com/lukas-krecan/JsonUnit/blob/master/tests/test-base/src/main/java/net/javacrumbs/jsonunit/test/base/AbstractAssertJTest.java#L759).

**Comment by tutufool** [comment]
Could you help me take a look at:
https://github.com/tutufool/JsonUnit/blob/master/json-unit-core/src/test/java/net/javacrumbs/jsonunit/core/internal/DifferenceTest.java#L270

I'm trying to ignore some attribute like 'timestamp' within the object in array, but I still need to check whether 'title' is same.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit#ignoring-paths

**Comment by tutufool** [comment]
No lucky, and this is the config I used:

`Configuration cfg = commonConfig().when(path("items.[*].timestamp"), thenIgnore()).when(path("items"), then(Option.IGNORING_ARRAY_ORDER))`

source:

```
            {
		   "items":[
		      {
		         "id":222,
		         "title":"Test Item 222",
		         "timestamp":7654321
		      },
		      {
		         "id":111,
		         "title":"Test Item 111",
		         "timestamp":7654321
		      }
		   ]
		}
```

**Comment by lukas-krecan** [comment]
Can you please specify what you are trying to do, what do you expect to happen and what happens instead (as described in the issue template which you apparently ignored).

**Comment by tutufool** [comment]
If you check my test case, you will find the test case failed for 

https://github.com/tutufool/JsonUnit/blob/master/json-unit-core/src/test/java/net/javacrumbs/jsonunit/core/internal/DifferenceTest.java#L311

Take above json as example, I'd like to:

1.  ignore item order inside 'items'
2.  ignore attribute 'timestamp' when compare each item since I think it's a noise
3.  Do NOT ignore attribute 'title' when compare, since I think it's a real biz filed.

**Comment by tutufool** [comment]
btw, this works if the 'timestamp' in the root level:
https://github.com/tutufool/JsonUnit/blob/master/json-unit-core/src/test/java/net/javacrumbs/jsonunit/core/internal/DifferenceTest.java#L226

But I'm no lucky to ignore it when it's in node of an array.

**Comment by lukas-krecan** [comment]
If I remember it correctly, the dot in `.[` should not be there
