### ISSUE TITLE
How to IGNORING_EXTRA_ARRAY_ITEMS when root node is an array

### ISSUE THREAD

**Issue by tutufool** [lukas-krecan/JsonUnit#235]
Control:

```
[
    {
        "name": "Leon",
        "number": 200
    },
    {
        "name": "Rocky",
        "number": 500
    }
]

```

test:

```
[
    {
        "name": "Leon",
        "number": 200
    },
    {
        "name": "Rocky",
        "number": 500
    },
    {
        "name": "Lin",
        "number": 600
    }
]
```

I tried below config but no lucky:

```
        Diff diff = Diff.create(control, test, "", "", Configuration.empty().when(path(""), then(Option.IGNORING_EXTRA_ARRAY_ITEMS)));
        //Diff diff = Diff.create(control, test, "", "", Configuration.empty().withOptions(Option.IGNORING_EXTRA_ARRAY_ITEMS));
```

Actually I dont know how to apply IGNORING_EXTRA_ARRAY_ITEMS to root node.

**Comment by lukas-krecan** [comment]
Hi, you can specify the option globally without using path.

**Comment by lukas-krecan** [comment]
Please describe what you expect and what exactly does not work. The commented-out line should work.

**Comment by tutufool** [comment]
My Bad, I pasted wrong order of control and test.

I just found:

```
            // if we expect more elements in the array than we get, it's error even when IGNORING_EXTRA_ARRAY_ITEMS
            if (expectedElements.size() > actualElements.size()) {
                structureDifferenceFound(context.length("at least " + expectedElements.size()), "Array \"%s\" has invalid length, expected: <at least %d> but was: <%d>.", path, expectedElements.size(), actualElements.size());
            }
```

I'm wondering whether we can introduce something similar in XmlUnit:

```
/**
 * May decide to up- or downgrade the severity of a difference.
 */
public interface DifferenceEvaluator {
    /**
     * May alter the outcome of a comparison.
     *
     * @return the new result of the comparison.
     */
    ComparisonResult evaluate(Comparison comparison, ComparisonResult outcome);
}
```

i.e.: give user last chance to revisit the Difference.

In my case, I'd like to have  features like Option.IGNORING_EXTRA_OR_LESS_ARRAY_ITEMS

**Comment by lukas-krecan** [comment]
JsonUnit is primarlily library for testing and it assumes that you have one of the JSONs under control. So IGNORING_EXTRA_OR_LESS_ARRAY_ITEMS does not make much sense. It's equivalent to ignoring the array which is supported. So appart of pointing you to DifferenceListener again, there is not much I can do to help you.
