### ISSUE TITLE
Add OSGI Manifest headers

### ISSUE THREAD

**Issue by amergey** [lukas-krecan/JsonUnit#24]
Hello,

Currently JsonUnit cannot be used in OSGI environment, OSGI Manifest headers are missing.
There is a maven plugin allowing to achieve that quite easilly 

I will create a pull request to propose a fix about that

**Comment by amergey** [comment]
I noticed a minor typo in my pull request, in json-unit-core/pom.xml, <Bundle-Name>JsonUnit Fluent</Bundle-Name> should be replaced with <Bundle-Name>JsonUnit Core</Bundle-Name>

Also sorry  about formatting changes, I noticed that too late

**Comment by lukas-krecan-gdc** [comment]
It's all right. Can you please check the changes I made here https://github.com/lukas-krecan/JsonUnit/commit/181f1ed9cf0f96df0958fd7b193ef65e511384af I will do similar changes to other modules as well, will let you check it and then I will release it. Or, if you have time, you can do the changes for the other modules (json-unit, json-unit-spring) and then I will just release it.

**Comment by amergey** [comment]
Thanks,

I have checked it.
I have submitted a new pull request as cleaning made json-unit-core bundle not working anymore in osgi.

https://github.com/lukas-krecan/JsonUnit/pull/26

**Comment by amergey** [comment]
Hello
I have tested 1.8.0 and it seems to work perfectly, thanks !

This issue is now fixed
