### ISSUE TITLE
Allow selection of Jackson 2 over Jackson 1 if both are in classpath

### ISSUE THREAD

**Issue by arhohuttunen** [lukas-krecan/JsonUnit#27]
Currently not possible to force usage of Jackson 2 over Jackson 1 if both are in the classpath.

This is a problem in a legacy project that has dependency to older version of Jackson 1 via a third party component.

It is possible to exclude version 1 from classpath in Maven surefire/failsafe but this is not possible in Eclipse.

**Comment by lukas-krecan** [comment]
I will do it, could you please explain in which case it is a problem? I'd like to know it, since I tried to make it as hassle-free as possible, so I am curious where I have failed.

**Comment by lukas-krecan** [comment]
Would a system property be OK for you? I would prefer to not polute the API by setting like this.

**Comment by arhohuttunen** [comment]
Yes, I think that will do just fine. Thank you for your quick reply.

The problem I am having is that there are Jackson 1.4.2 (which I can't update) and Jackson 2.x in the classpath. Unfortunately json-unit requires 1.9.13 when 1.x is used. This is why I would prefer the option to force usage of 2.x.

**Comment by lukas-krecan** [comment]
Jackson 1 is used only if the class being compared extends from org.codehaus.jackson.JsonNode or contains Jackson1 annotation. It feels wrong to use Jackson 2 to serialize such classes (annotations will be ignored). I managed to make json-unit Jackson 1.4 compatible which should hopefully solve your problem. If not, please let me know and I will add the system property.

**Comment by lukas-krecan** [comment]
Released as 1.9.0

**Comment by lukas-krecan** [comment]
I have been thinking about your use-case and I have realized that you may have both Jackson 1 and 2 annotation on a class. In such case I would do something like this

    assertJsonEquals(expected, serializeWithJackson1(value));
    assertJsonEquals(expected, serializeWithJackson2(value));
or create a wrapper method like 

    assertJacskon1Equals(expected, value);

**Comment by arhohuttunen** [comment]
Actually I'm not sure if we are using Jackson annotations at all on these classes. They are entity classes that do have other annotations though. But I just realized that we are using things like jackson-datatype-hibernate. I can't check right now but I will let you know if I find the root cause.

**Comment by lukas-krecan** [comment]
I have have realized what's going on. The mechanism that was detecting whether or not class contains Jackson 1 annotations was not compatible with 1.4 and was failing. If that was the case, JsonUnit 1.9.0 should help.

**Comment by arhohuttunen** [comment]
Makes perfect sense now. JsonUnit 1.9.0 solved the problem, thank you.
