### ISSUE TITLE
Comparing single value and arrays

### ISSUE THREAD

**Issue by jmini** [lukas-krecan/JsonUnit#281]
I have a document that can support both single value or array.

Example corresponding schema:

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "title": "Address",
    "description": "An address representation",
    "properties": {
        "v": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ]
        }
    }
}
```

Example values:

Example 1)
```json
{
    "v": "foo"
}
```

Example 2)
```json
{
    "v": ["foo", "bar"]
}
```

Example 3)
```json
{
    "v": ["foo"]
}
```

I am using following feature of Jackson to support this:

```java
    @JsonProperty("v")
    @JsonFormat(with = { JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY, JsonFormat.Feature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED })
    private List<String> v;
```

This works well. But now I have the side effect that when I parse `Example 3)` it gets serialized to `Example 1)`.
This doesn't matter for our business. Both are really considered to be the same.

I am looking for a way to tell that both `Example 1)` and `Example 3)` are the same when doing the comparison with JsonUnit. I could not find anything in the Options.

I would appreciate any pointer on how to implement something like this.

I just read about "Jackson Object Mapper customization" and I will give this a try.
https://github.com/lukas-krecan/JsonUnit#jackson-object-mapper-customization

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I would recommend to try [custom matcher](https://github.com/lukas-krecan/JsonUnit#matchers).

**Comment by lukas-krecan** [comment]
Hi, did custom matcher help?
