### ISSUE TITLE
Add support for placing matchers within surrounding context

### ISSUE THREAD

**Issue by bobtiernay-okta** [lukas-krecan/JsonUnit#290]
**Is your feature request related to a problem? Please describe.**
It would be nice to allow for matchers such as `regex` to be able support the following:

```java
assertThatJson("{\"test\": \"This is some text followed by: ABCD, followed by this\"}")
    .isEqualTo("{\"test\": \"This is some text followed by: ${json-unit.regex}[A-Z]+, followed by this\"}");
```

However, this may cause expression parsing issues as the regex falls outside of the matcher expression.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
Another alternative is to document the following (untested) solution:
```java
assertThatJson("{\"test\": \"This is some text followed by: ABCD, followed by this\"}")
    .isEqualTo("{\"test\": \"${json-unit.regex}\QThis is some text followed by: \E[A-Z]+\Q, followed by this\E\"}");
```

**Additional context**
This actually comes up pretty frequently.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I see your point, the workaround is indeed possible but it [sucks](https://github.com/lukas-krecan/JsonUnit/commit/3489e20a82827be4c0bd7f2f1cc4d83225f3024d). On the other hand, the solution you have proposed leads to a rabbit hole. If we support `${json-unit.regex}` we should support `${json-unit.any-*}` expressions, matchers and before I know it, I would end up with my own expression language.

I have to think about it, there may be some more elegant solution. Maybe something connected to [custom matchers](https://github.com/lukas-krecan/JsonUnit#custom-matchers)

**Comment by bobtiernay-okta** [comment]
>  and before I know it, I would end up with my own expression language.

Wondering if creating something similar to Apache Commons Text's `StringSubstitutor` might be enough:
https://github.com/apache/commons-text/blob/master/src/main/java/org/apache/commons/text/StringSubstitutor.java

Although maybe that's too much even?

**Comment by lukas-krecan** [comment]
I have decided not to implement this. I prefer to let it up to users to implement some helper matching their use-case. You can for example do something like [this](https://github.com/lukas-krecan/JsonUnit/commit/9bb89350e9f3840e4c96566826d8c3c9dd7a7037)

**Comment by bobtiernay-okta** [comment]
I understand your thinking. Perhaps it would be useful to add a note to the README about that pattern? It likely would be useful guidance to several folks.

**Comment by lukas-krecan** [comment]
Will do, thanks
