### ISSUE TITLE
fail to install json-unit-assertj dependecies

### ISSUE THREAD

**Issue by gotesj** [lukas-krecan/JsonUnit#293]
I'm trying to use the json-unit-assertj module but I keep getting the following error from maven:
`[ERROR] Failed to execute goal on project json-unit-json-path: Could not resolve dependencies for project net.javacrumbs.json-unit:json-unit-json-path:bundle:2.19.1-SNAPSHOT: Failed to collect dependencies at com.jayway.jsonpath:json-path:jar:2.4.0: Failed to read artifact descriptor for com.jayway.jsonpath:json-path:jar:2.4.0: Could not find artifact org.eclipse.sensinact.gateway.nthbnd:parent:pom:1.5-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]`
I tried cloning the project but the same issue is seen

**Comment by lukas-krecan** [comment]
It seems you are trying to build the project with some strange configuration. **You do not need to build it in order to use the project**, just follow the instructions in README. If you have a reason to build it, please describe why and what are you trying to achieve, otherwise I am not able to help you.

**Comment by gotesj** [comment]
I've added the following to my pom
        <dependency>
            <groupId>net.javacrumbs.json-unit</groupId>
            <artifactId>json-unit-assertj</artifactId>
            <version>2.19.0</version>
            <scope>test</scope>
        </dependency>

and it failed to build my project

Here is the full pom

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.test.Automation</groupId>
        <artifactId>TestAutomation</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>junit.automation</artifactId>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
    </properties>

    <repositories>
        <repository>
            <id>bintray</id>
            <url>http://dl.bintray.com/epam/reportportal</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>jgit-repository</id>
            <url>https://repo.eclipse.org/content/groups/releases/</url>
        </repository>
    </repositories>

    <dependencies>
        
        
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.55</version>
        </dependency>
        <dependency>
            <groupId>com.nordstrom.tools</groupId>
            <artifactId>junit-foundation</artifactId>
            <version>9.1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-junit5</artifactId>
            <version>4.0.3</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>4.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.14.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.8.1</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>7.4.1.jre8</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.21</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20190722</version>
        </dependency>
        
        <dependency>
            <groupId>com.thoughtworks.xstream</groupId>
            <artifactId>xstream</artifactId>
            <version>1.4.11.1</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>7.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.17.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.gitlab4j</groupId>
            <artifactId>gitlab4j-api</artifactId>
            <version>4.15.7</version>
        </dependency>
        <dependency>
            <groupId>org.everit.json</groupId>
            <artifactId>org.everit.json.schema</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>net.javacrumbs.json-unit</groupId>
            <artifactId>json-unit-assertj</artifactId>
            <version>2.19.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>RELEASE</version>
            <scope>test</scope>
        </dependency>
    </dependencies>


    <build>
        <filters>
            
            <filter>${report-conf}</filter>
        </filters>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <pluginManagement>
            <plugins>
                
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-dependency-plugin</artifactId>
                                        <versionRange>[1.0.0,)</versionRange>
                                        <goals>
                                            <goal>properties</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <execute/>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>getClasspathFilenames</id>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
                <configuration>
                    <excludes>
                        <include>**/FailingTests.java</include>
                    </excludes>
                    <properties>
                        <configurationParameters>
                            junit.jupiter.extensions.autodetection.enabled = true
                        </configurationParameters>
                    </properties>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>`

Then when I execute the mvn command I get the following

`mvn -U clean install -Dreport-conf="C:\tmp\report-conf.properties" -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building junit.automation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://dl.bintray.com/epam/reportportal/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/maven-metadata.xml
Downloading: https://jitpack.io/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/maven-metadata.xml
Downloading: https://repo.eclipse.org/content/groups/releases/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/maven-metadata.xml
Downloading: http://dl.bintray.com/epam/reportportal/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/parent-1.5-SNAPSHOT.pom
Downloading: https://jitpack.io/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/parent-1.5-SNAPSHOT.pom
Downloading: https://repo.eclipse.org/content/groups/releases/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/parent-1.5-SNAPSHOT.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/sensinact/gateway/nthbnd/parent/1.5-SNAPSHOT/parent-1.5-SNAPSHOT.pom
Downloading: http://dl.bintray.com/epam/reportportal/org/junit/jupiter/junit-jupiter/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/maven-metadata.xml
Downloading: https://repo.eclipse.org/content/groups/releases/org/junit/jupiter/junit-jupiter/maven-metadata.xml
Downloading: https://jitpack.io/org/junit/jupiter/junit-jupiter/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/maven-metadata.xml (962 B at 1.4 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.170 s
[INFO] Finished at: 2020-10-26T08:34:53+02:00
[INFO] Final Memory: 19M/216M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project junit.automation: Could not resolve dependencies for project com.test.Automation:junit.automation:jar:1.0-SNAPSHOT: Failed to collect dependencies at net.javacrumbs.json-unit:json-unit-asse
rtj:jar:2.19.0 -> net.javacrumbs.json-unit:json-unit-json-path:jar:2.19.0 -> com.jayway.jsonpath:json-path:jar:2.4.0: Failed to read artifact descriptor for com.jayway.jsonpath:json-path:jar:2.4.0: Could not find artifact org.eclips
e.sensinact.gateway.nthbnd:parent:pom:1.5-SNAPSHOT in bintray (http://dl.bintray.com/epam/reportportal) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

Thank you for your help

**Comment by lukas-krecan** [comment]
Can you please try adding Maven Central repository to your `repositories`? It seems that json-path has some dependency that is not in the repositories you are using. In next few days I will dig into it deeper.

**Comment by gotesj** [comment]
I've added the following to my repositories
`        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>`

Still no luck, same issue.
I really appreciate the help

**Comment by lukas-krecan** [comment]
I am sorry, I tried your POM and it works for me. I have no idea what's wrong with your project. `org.eclipse.sensinact.gateway.nthbnd:parent:pom:1.5-SNAPSHOT ` is not in JsonUnit dependencies.
