### ISSUE TITLE
Invoking isArray().containsOnly() fails if the expected value is a String containing only numeric symbols

### ISSUE THREAD

**Issue by rromanik** [lukas-krecan/JsonUnit#295]
**Bug description**
1. I'm using AssertJ variant of the API.
I'm using the following library versions:
json-unit-assertJ: 2.19.0
Jackson: 2.9.10

2. The following example reproduces the bug:
```
    @Test
    public void verifyIsArrayContainsString() {
        String s = "{\"id\":\"1\", \"children\":[{\"parentId\":\"1\"}]}";

        JsonAssertions.assertThatJson(s)
                .inPath("children[*].parentId")
                .isArray()
                .containsOnly("1");
    }
```

3. I expected the above described test to pass but it returns: 
```
ava.lang.AssertionError: [Different value found in node "children[*].parentId"]  
Expecting ArrayList:  
  <["1"]>  
to contain only:  
  <["1"]>  
element(s) not found:  
  <["1"]>  
and element(s) not expected:  
  <["1"]>  
when comparing values using JsonComparator
```

**Note**: the same test passes if letters are used instead of numbers, e.g.:
```
    @Test
    public void verifyIsArrayContainsString() {
        String s = "{\"id\":\"a\", \"children\":[{\"parentId\":\"a\"}]}";

        JsonAssertions.assertThatJson(s)
                .inPath("children[*].parentId")
                .isArray()
                .containsOnly("a");
    }
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. The root cause is that JsonUnit parses the expected value as JSON to let you write `.containsOnly("{\"a\":1}")`. So "1" is parsed as JSON containing number 1. In order to disambiguate the expression, you have to use `.containsOnly(value("1"))`.
