### ISSUE TITLE
Option to ignore order in map should be available

### ISSUE THREAD

**Issue by ajayvedwa** [lukas-krecan/JsonUnit#30]
I am getting a map which comes in different order in each request. Is there any way to ignore order of map? The below screenshot shows the response from two json where tree_topics comes at order one while in other hit it comes second. Please help

![image](https://cloud.githubusercontent.com/assets/783164/13670957/05a90ddc-e6f3-11e5-8292-a1e2d88906ef.png)

**Comment by lukas-krecan** [comment]
JsonUnit ignores the order of JSON fields by default. I assume there is some other difference that causes the problem, can you please post here the error message?
