### ISSUE TITLE
How to ignore a parameter in map value objects?

### ISSUE THREAD

**Issue by rromanik** [lukas-krecan/JsonUnit#302]
**This is a question about 'whenIgnoringPaths' method functionality**

Given the following expected and actual JSON strings:
```
		String expected = "{\"a\":{\"id\":\"a\",\"action\":\"update\",\"name\":\"page1\"}," +
				"\"b\":{\"id\":\"b\",\"action\":\"update\",\"name\":\"page2\"}}";
		String actual = "{\"a\":{\"id\":\"a\",\"name\":\"page1\"}," +
				"\"b\":{\"id\":\"b\",\"name\":\"page2\"}}";
```
is it possible to assert them for equality while ignoring the 'action' field, since it's optional?
For example, as in the following sample test
```
		JsonAssertions.assertThatJson(actual)
				.whenIgnoringPaths("$.*.action", "*.action")
				.isEqualTo(expected);
```
but here, of course, the provided paths do not help.

Paths such as "a.action" or "b.action" cannot be used since the JSON can have many more keys (IDs), and the IDs can be random strings.

**Comment by lukas-krecan** [comment]
Hi, I am not sure I understand the question. `$..action` should, in my opinion, work.

**Comment by rromanik** [comment]
Yes, you're right, the `$..action` works (as well as `$.*.action`), but only if 'actual' and 'expected' are swapped in the test:
```
JsonAssertions.assertThatJson(expected)
				.whenIgnoringPaths("$..action")
				.isEqualTo(actual);
```
Thank you, @lukas-krecan
