### ISSUE TITLE
Support asserting for absent element

### ISSUE THREAD

**Issue by filiphr** [lukas-krecan/JsonUnit#314]
**Is your feature request related to a problem? Please describe.**

When we have a rather large json structure I want to validate the presence of some fields and absence of some.
Currently, I need to write a hamcrest matcher in order to achieve that. 

**Describe the solution you'd like**

It would be great if I can use something like `${json-unit.absent}`.

The json looks something like:

```
[
  {
    name: '', taskVar: '...', processVar: '...', ....,
    customer: { ... },
    root: {
      ...
    }
  },
...
]
```

It is an array with a lot of entries and each entry has complex structure. I would like to assert the presence of some and the explicit absence of certain elements in certain levels.

e.g. Write something like:

```
assertThatJson(json)
    .when(Option.IGNORING_EXTRA_FIELDS, Option.IGNORING_ARRAY_ORDER)
    .isEqualTo("["
                  + " {"
                  + "    taskVar: 'Process Task 1', processVar: 'Process 1', customerName: 'Gonzo',"
                  + "    root: {"
                  + "      customerName: 'Kermit 1', processVar: 'Process 1', taskVar: '${json-unit.absent}'"
                  + "    }"
                  + "  },"
                  + " {"
                  + "    taskVar: 'Process Task 2', processVar: 'Process 2', customerName: 'Fozzie',"
                  + "    root: {"
                  + "      customerName: 'Kermit 2', processVar: 'Process 2', taskVar: '${json-unit.absent}'"
                  + "    }"
                  + "  }"
                  + "]");
```

**Describe alternatives you've considered**

I know that I can use a hamcrest matchers, but that would mean that I need to add it every time and I would need to assert for `null`, but this is not 100% correct, since `null` doesn't have to mean that it is absent from the json.

**Additional context**

If the idea is interesting I can try to have a look at providing a PR for this.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. JsonUnit currently supports this
```
assertThatJson(json).node("[*].root.taskVar").isAbsent()
```
Which doeas what you are looking for. Would it be enough for you?

Adding `${json-unit.absent}` feels strange but I undersand the need for it. Let me think about it, there are usually some unintended consequences.

**Comment by lukas-krecan** [comment]
`assertThatJson(json).inPath("[*].root.taskVar").isArray().isEmpty()` works, but does not have helpful error message.

**Comment by lukas-krecan** [comment]
If you want, please provide some draft PR, it might be interesting feature to have.

**Comment by lukas-krecan** [comment]
I have been thinking about it and maybe a simpler alternative could be `assertThatJson(json).hasNoNodesInPath("[*].root.taskVar")` Would it be useful for your use-case? (Maybe with a better name)

**Comment by lukas-krecan** [comment]
Even better idea, I will fix `assertThatJson(json).node("[*].root.taskVar").isAbsent()`

**Comment by filiphr** [comment]
I've been wanting to create a PR, but always keep postponing it.

Your proposals are interesting. However, it might not work if I want to check that one element does not have that value and another one does. That's why I prefer the single json `isEqualTo` :).

**Comment by lukas-krecan** [comment]
That's why we have `and` operator

```
assertThatJson("{\"test\":{\"a\":1, \"b\":2, \"c\":3}}").and(
    a -> a.node("test.a").isEqualTo(1),
    a -> a.node("test.b").isEqualTo(2)
);
```

(in Kotlin it looks even better)

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit/pull/319

**Comment by lukas-krecan** [comment]
Release 2.23.0 where `assertThatJson(json).inPath("[*].root.taskVar").isAbsent()` has better failure message. Feel free to try and if you do not like it feel free to provide the PR.
