### ISSUE TITLE
[Feature] Configuration to compare numbers with equivalent string values

### ISSUE THREAD

**Issue by 69pmb** [lukas-krecan/JsonUnit#329]
Thanks for this useful library !
But I stumble on a small issue.
I would like that two json field to be equals but one is a number and the other is a string:
```bash
Different value found in node "forecast.forecastday[0].hour[2].chance_of_rain", expected: <"0"> but was: <0>.
```
Would it be possible to have a configuration to consider these fields as equals ?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please explain your use-case? The library assumes that the "expected" value is under your control, so my question is what's preventing you from changing the expected value? I am not questioning your use-case, I am just curious what it is.
