### ISSUE TITLE
Let json-unit.regex work with numbers

### ISSUE THREAD

**Issue by k1w1m8** [lukas-krecan/JsonUnit#356]
Currently I can ignore a number using "json-unit.any-number" as the expected value

But "${json-unit.regex}[0-9]+" doesn't work as an expected value.

Can this be added?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. To me, the regex matcher only makes sense on strings, it's does not make much sense on other types like numbers, booleans or objects. If you want, you can implement it yourself using the [custom matcher](https://github.com/lukas-krecan/JsonUnit#matchers).

**Comment by k1w1m8** [comment]
Ah yeah, it comes back to this idea of are we comparing the JSON model or the JSON text. 

Comparing the text it makes a lot of sense. But comparing the model it doesn't make much sense.
