### ISSUE TITLE
IGNORING_EXTRA_FIELDS option not working for Fluent assertions

### ISSUE THREAD

**Issue by ajayvedwa** [lukas-krecan/JsonUnit#36]
I am using 1.10 version of json-unit-fluent. On running with following JSON values, I am getting the message :-

FAILED: compareJSONFiles
java.lang.AssertionError: JSON documents are different:
Different keys found in node "data". Expected [monitortrendingentity], got [company, monitortrendingentity].  Extra: "data.company"

Please look into this.

JsonFluentAssert.assertThatJson("{  \"status\": \"success\",  \"message\": \"spiking topic data populated successfully.\",  \"data\": {    \"monitortrendingentity\": [      {        \"companyid\": 0      }    ],    \"company\": {      \"ticker\": \"ge\"    }  },  \"statuscode\": \"request_success\"}").isEqualTo("{  \"status\": \"success\",  \"statuscode\": \"request_success\",  \"message\": \"spiking topic data populated successfully.\",  \"data\": {    \"monitortrendingentity\": [      {        \"companyid\": 0      }    ]  }  }").when(Option.IGNORING_ARRAY_ORDER,Option.IGNORING_EXTRA_FIELDS,Option.IGNORING_EXTRA_ARRAY_ITEMS);

**Comment by lukas-krecan** [comment]
Hi, the problem is that you have to specify the options **before** the comparison. You are not the first one who made the same "mistake", unfortunately it's quite tricky to fix such API issues once it's released. I will try anyway. Thanks for reporting it.

**Comment by ajayvedwa** [comment]
Using it before or after makes difference in error message.

JsonFluentAssert.assertThatJson("{\"status\":\"success\",\"message\":\"data stream data populated successfully.\",\"data\":{\"stream\":{\"resultlist\":[{\"inserttime\":1459444233283,\"groupid\":542299453,\"date\":\"2016-03-31 10:10:33\",\"score\":0,\"dayid\":-1,\"sourceid\":\"452483\",\"insertdate\":\"mar 31, 2016\",\"insertdate1\":\"mar 31\"}],\"total\":0,\"startminuteid\":8018471,\"endminuteid\":7997728,\"scope\":2}},\"statuscode\":\"request_success\"}").when(Option.IGNORING_ARRAY_ORDER, Option.IGNORING_EXTRA_FIELDS, Option.IGNORING_EXTRA_ARRAY_ITEMS).isEqualTo("{\"status\":\"success\",\"message\":\"data stream data populated successfully.\",\"data\":{\"stream\":{\"resultlist\":[{\"inserttime\":1459444233283,\"groupid\":542299453,\"date\":\"2016-03-31 10:10:33\",\"score\":0,\"dupcount\":0,\"dayid\":-1,\"sourceid\":\"452483\",\"insertdate\":\"mar 31, 2016\",\"insertdate1\":\"mar 31\"}],\"total\":0,\"startminuteid\":8018471,\"endminuteid\":7997728,\"scope\":2}},\"statuscode\":\"request_success\"}");

Give me output as failure error as :-

JSON documents are different:
Array "data.stream.resultlist" has different content. Missing values [{"inserttime":1459444233283,"groupid":542299453,"date":"2016-03-31 10:10:33","score":0,"dupcount":0,"dayid":-1,"sourceid":"452483","insertdate":"mar 31, 2016","insertdate1":"mar 31"}]


While putting before the comparison gives me 

JsonFluentAssert.assertThatJson("{\"status\":\"success\",\"message\":\"data stream data populated successfully.\",\"data\":{\"stream\":{\"resultlist\":[{\"inserttime\":1459444233283,\"groupid\":542299453,\"date\":\"2016-03-31 10:10:33\",\"score\":0,\"dayid\":-1,\"sourceid\":\"452483\",\"insertdate\":\"mar 31, 2016\",\"insertdate1\":\"mar 31\"}],\"total\":0,\"startminuteid\":8018471,\"endminuteid\":7997728,\"scope\":2}},\"statuscode\":\"request_success\"}").isEqualTo("{\"status\":\"success\",\"message\":\"data stream data populated successfully.\",\"data\":{\"stream\":{\"resultlist\":[{\"inserttime\":1459444233283,\"groupid\":542299453,\"date\":\"2016-03-31 10:10:33\",\"score\":0,\"dupcount\":0,\"dayid\":-1,\"sourceid\":\"452483\",\"insertdate\":\"mar 31, 2016\",\"insertdate1\":\"mar 31\"}],\"total\":0,\"startminuteid\":8018471,\"endminuteid\":7997728,\"scope\":2}},\"statuscode\":\"request_success\"}").when(Option.IGNORING_ARRAY_ORDER, Option.IGNORING_EXTRA_FIELDS, Option.IGNORING_EXTRA_ARRAY_ITEMS);

Output error :-

JSON documents are different:
Different keys found in node "data.stream.resultlist[0]". Expected [date, dayid, dupcount, groupid, insertdate, insertdate1, inserttime, score, sourceid], got [date, dayid, groupid, insertdate, insertdate1, inserttime, score, sourceid]. Missing: "data.stream.resultlist[0].dupcount" 


In both the cases the output error in HIT 2 makes more sense. Can you check why there is difference in both the hit.

**Comment by lukas-krecan** [comment]
Hi, it's simple. If you call `when()` method AFTER  `isEqualTo()`, it's effectively ignored (`isEqualTo()` is called before `when()`, in Java it's not possible to do it otherwise). Since the options are ignored, the library is not ignoring array order so it is able to compare first item of expected array with first item of actual array which leads to better error message. See the discussion here https://github.com/lukas-krecan/JsonUnit/issues/28 for more details.

If you call `when()` method BEFORE  `isEqualTo()` the options are not ignored. The comparison fails since you expect `"dupcount":0` in `isEqualTo()` and it is not present in the actual document. 

In version 1.11.0, you will get compile-time warning if you use `when` after assertion.
