### ISSUE TITLE
Support for ${json-unit.any-uuid}

### ISSUE THREAD

**Issue by juzerali** [lukas-krecan/JsonUnit#362]
I need to make sure that the value is a generated uuid

Support `${json-unit.any-uuid}` assertions

**Describe alternatives you've considered**
`any-string` matcher

**Comment by lukas-krecan** [comment]
This feels too specific to be in the library, I would recommend you to use [custom matcher.](https://github.com/lukas-krecan/JsonUnit#matchers)

**Comment by juzerali** [comment]
I feel there should be a library where a lot of these common assertions are maintained.
