### ISSUE TITLE
Cannot compare a stringified JSON property to a JSON resource.

### ISSUE THREAD

**Issue by corey-aloia** [lukas-krecan/JsonUnit#369]
First of all, awesome library! 

I am not sure if this is a bug, or if I just can't find the right mix. I have spent longer than I am willing to admit on this. 

I have a json object which has a 'message' property, where the value of that property is a stringified json. 

So, this works (using gson library):

```
    JsonObject event = JsonParser.parseString(record.value()).getAsJsonObject(); // record.value() is a strinigied json
    JsonObject eventMessage = JsonParser
        .parseString(event.get("message").getAsString()) 
        .getAsJsonObject(); //message is a property, which is itself stringified json.
    assertThatJson(eventMessage)
        .isEqualTo(resource("event-message-section-only.json"));
```

I want to be able to do this with the super-cool json-unit library. I have tried various ways, which seem like they would work, such as:
```
  assertThatJson(json(inPath(record.value(), "$.message"))) // added the extra json() conversions to be extra sure
      .isEqualTo(json(resource("event-message-section-only.json")));
```

Thanks!

**Comment by lukas-krecan** [comment]
Hi, so it's a Json encoded as a string in another Json? There is currently no support for that in the library, the easiest way is to deserialize it before the assertion and then compare just the one field. Alternatively, I can imagine using a [custom matcher](https://github.com/lukas-krecan/JsonUnit#custom-matchers) that would call `assertThatJson()` from the `matches` method .

**Comment by corey-aloia** [comment]
Yes, exactly. I guess I was expecting the `json()` method to force the string to be a json object when comparing.

Thanks

**Comment by lukas-krecan** [comment]
Unfortunately, a string like `"something"` is also a valid JSON object.
