### ISSUE TITLE
Simpler JSON string literals

### ISSUE THREAD

**Issue by tstavinoha** [lukas-krecan/JsonUnit#37]
Hello

I was wondering if there is a possibility to implement less strict definitions of JSON literals for expected value.

For example, to reduce this:
assertThatJson(responseBody).isEqualTo("{\"property1\":\"value1\", \"property2\":{[\"item1\", \"item2\"]}}");

To this:
assertThatJson(responseBody).isEqualTo("{property1:'value1', property2:{['item1', 'item2']}}");

More or less, to allow syntax closer to the way it is written in JavaScript, in order to reduce the number of escaped double quotes by using single quotes for strings, and omitting them for field names.

The reason for this is to improve readability. It's hard to see the actual expected JSON when there is so many escaped quotes. These examples are short, but in a real world scenario JSONs are usually much longer.

An alternative approach could be to store expected JSONs as files and load them, but that way expected values are far away from the test, again hurting readability.

**Comment by lukas-krecan** [comment]
Great idea.

**Comment by lukas-krecan** [comment]
You can try freshly released version 1.12.0 once it's propagated to the central repo (should be in few hours).

**Comment by tstavinoha** [comment]
Wow, that was FAST! Great job!
Already readability is much improved, however the double quotes on strings are still required. I see that you use Jackson in parts of your code, so maybe you would agree to also add:

` lenientMapper.configure(JsonParser.Feature.ALLOW_SINGLE_QUOTES, true);`

in Jackson factories?

**Comment by lukas-krecan** [comment]
Sounds reasonable, I will do it over the weekend

**Comment by lukas-krecan** [comment]
Released as 1.12.1, enjoy

**Comment by tstavinoha** [comment]
You rock, man! :)
