### ISSUE TITLE
Failing test when json has a whitespace difference in the array

### ISSUE THREAD

**Issue by norbert-csibra-msm** [lukas-krecan/JsonUnit#38]
Hello,

I have a test like this:

```java
@Test
public void failure_on_whitespace() {
    List<String> actual = Lists.newArrayList("{\"a\":1}", "{\"a\" :2}");
    List<String> expected = Lists.newArrayList("{\"a\":1}", "{\"a\":2}");

    assertThatJson(actual).when(IGNORING_ARRAY_ORDER).isEqualTo(expected);
}
```

The 2 json are the same, but the second one in the first List has an extra whitespace.
When I run the test, it is failing:

```
15:02:13.922 [main] DEBUG n.j.jsonunit.difference.diff - JSON documents are different:
Different value found in node "". Expected "{"a":2}", got "{"a" :2}".
15:02:13.926 [main] DEBUG n.j.jsonunit.difference.values - Comparing expected:
"{\"a\":2}"
------------
with actual:
"{\"a\" :2}"

15:02:13.929 [main] DEBUG n.j.jsonunit.difference.diff - JSON documents are different:
Array "" has different content. Missing values ["{\"a\":2}"], extra values ["{\"a\" :2}"]
15:02:13.929 [main] DEBUG n.j.jsonunit.difference.values - Comparing expected:
["{\"a\":1}","{\"a\":2}"]
------------
with actual:
["{\"a\":1}","{\"a\" :2}"]

15:02:13.929 [main] DEBUG n.j.jsonunit.difference.diff - JSON documents are different:
Array "" has different content. Missing values ["{\"a\":2}"], extra values ["{\"a\" :2}"]
15:02:13.929 [main] DEBUG n.j.jsonunit.difference.values - Comparing expected:
["{\"a\":1}","{\"a\":2}"]
------------
with actual:
["{\"a\":1}","{\"a\" :2}"]


java.lang.AssertionError: JSON documents are different:
Array "" has different content. Missing values ["{\"a\":2}"], extra values ["{\"a\" :2}"]
```

In the README you state that _"When the values are compared, order of elements and whitespaces are ignored"_.
If I'm trying to compare two strings, not arrays, then it's working fine, e.g.:

```java
@Test
public void passed_when_comparing_simple_strings() {
    String actual = "{\"a\" :2}";
    String expected = "{\"a\":2}";

    assertThatJson(actual).isEqualTo(expected);
}
```

Tried with the json-unit-fluent library, version 1.12.1.
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

Could you check this issue?

Regards,
Norbert

**Comment by lukas-krecan** [comment]
Hi, I think the issue is that you have two lists of Strings. Imagine you had 
    List<String> actual = Lists.newArrayList("one", "two");
    List<String> expected = Lists.newArrayList("one", "twooo");

In such case the behavior would not we surprising at all. In other words, the library has no way to guess that there is a JSON in your strings. If you use an object a as parameter, the library just creates a JSON representation of the object and uses the representation for comparison. In this case it compares two arrays of strings. There are two possible solutions

1. Use JSON arrays

    String actual = "[{\"a\":1}, {\"a\" :2}]";
    String expected = "[{\"a\":1}, {\"a\":2}"];

2. Do not use strings, but objects

    List<String> actual = Lists.newArrayList(singletonMap("a", 1), ...);

but I do not think that it's what you want. May you please let me know what your use-case is?

**Comment by norbert-csibra-msm** [comment]
Yes, you are right, I opened this issue rashly.
I assumed that the mapper will parse the json in the array, but that was just stupid.
I solved this by reading the string to a JsonNode.
Sorry and thanks for the quick answer. :)
