### ISSUE TITLE
Can't compare String node with Integer Value

### ISSUE THREAD

**Issue by DaGeRe** [lukas-krecan/JsonUnit#39]
Hi,

I am currently trying to compare a node, which has an String value, that only contains numbers, for example:

JsonFluentAssert.assertThatJson("{\"test\": \"2\"}").node("test").isEqualTo("2");

I can not find a way to get this running - it always says, that '2' is expected but it got ''"2"'. It seems like JsonUnit casts the "2" to an int, and is therefore not capable of checking the value correctly. Is this right, or is there another way of comparing string node values?

**Comment by lukas-krecan** [comment]
Yes, there is a bit of magic where the library tries to guess if there is a JSON in the string or not. Quoting should help.

JsonFluentAssert.assertThatJson("{\"test\": \"2\"}").node("test").isEqualTo("\"2\"")

**Comment by DaGeRe** [comment]
Thanks, this solves the problem.
