### ISSUE TITLE
"anonymous" custom matchers i.e. without the json-unit:matches prefix

### ISSUE THREAD

**Issue by k1w1m8** [lukas-krecan/JsonUnit#391]
I would like to create my own expressions that work consistently for both XML and JSON, e.g ${my.ignore} or ${my.regex}.

I already created that for XMLUnit using their DifferenceListener. This is possible as the XMLUnit DifferenceListener, has the ability to return a value from the differenceFound() method to control how the difference should be dealt with.

Currently json-unit DifferenceListener doesn't seem to have that feature so I am currently using json-unit syntax for ignore and regex. This is confusing and jarring for users who need to work with both XML and JSON.

So, would it be possible to extend json-unit DifferenceListener  to do the same?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I am afraid that our DifferenceListener is not a great place for that. I do not know what your use-case is, but isn't it possible to preprocess the expected value and replace `${my.ignore}` by `${json-unit.ignore}`?

**Comment by k1w1m8** [comment]
Indeed that can be done. I was thinking that it might be confusing, as the
translated version would show up in error messages, etc. Which again is
jarring for a user who doesn't understand what it happening under the
covers.

**Comment by lukas-krecan** [comment]
That's true. Let me think how to make it more configurable. Do you have list of expressions that you need to translate?

**Comment by k1w1m8** [comment]
Here are the tags/expressions I've created that work "generically" in various contexts, e.g. properties files, text files and XML files (using XMLUnit DifferenceListener).

```
${jet.regex}<regex value> - matches the actual field using provided regex
${jet.ignore} - ignore actual field
${jet.capture}<variable name> - capture actual field into a variable
${jet.embedded.xml}<embedded XML> - parse actual field as an XML document and compare it as such
```

These are what I use in JSON files, which parallel the above

```
${json-unit.regex}
${json-unit.ignore}
${json-unit.matches:capture
${json-unit.matches:embedded - embedded JSON document
```

So I guess, to make it work we'd need:

* configurable prefix (json-unit->jet)
* upgrade matches feature to optionally allow "anonymous" usage, i.e. "matches:" part is not required, but names not allowed to clash with builtins.

Seems like both of these are good incremental improvements. I guess they would be reasonably simple to implement and certainly simple for me to use. 

In contrast extending difference listener would be more complex but would also introduce a general and powerful new extensibility feature which can be used for many different use cases. It would be a little more complex for me to use but would be logically consistent to how I use XMLUnit.

Either would meet my needs.

**Comment by lukas-krecan** [comment]
This is quite a niche requirement and I do not want to develop a heavy feature for that. I think that current matchers are quite powerfull and can be used for this, you need to translate the expected values to 

```
${json-unit.matches:jet.regex}...
${json-unit.matches:jet.ignore}
${json-unit.matches:jet.capture...
${json-unit.matches:jet.embedded}...
```
and implement corresponding matchers. I think that the error messages will contian name of the matchers which is what the users expect and everything should work fine. If that's not the case, we can figure out how to enhance the error messages.

**Comment by k1w1m8** [comment]
Good idea. I can easily replace the standard matchers and add the translation step, and it would be more consistent. I can give it a try. 

The final stage would be to implement "anonymous matchers" above which would mean I could take out the translation step.

Would you accept a pull request for that?

**Comment by k1w1m8** [comment]
So here is how it looks in a unit test of suggestion above.

Anonymous matchers would reduce the "cognitive dissonance" here.
```
*** Test failed
Report was: 
*  Expected ${jet.regex}abc[0-9]+ does not match actual xxx
  Expected:
  {
    "o" : "${json-unit.matches:jet.regex}abc[0-9]+"
  }
  Actual:
  {
    "o" : "xxx"
  }
```

**Comment by lukas-krecan** [comment]
I have been thinking about a matcher, that would not require the json-unit prefix but then I didn't see much value in it. But maybe it's worth a try. I would accept a PR if it's lightweight enough 😈 . Or I can try to do it myself.

**Comment by k1w1m8** [comment]
Great. I would be more than happy if you have time.

So many open source projects that require pull requests, so little time.

I'm still annoyed with myself for promising to help with surefire and JUnit5 dynamic tests which I never followed through with.

;-)

**Comment by k1w1m8** [comment]
Far out I think I closed this by mistake,

**Comment by k1w1m8** [comment]
I just realised, I didn't update for "quite some time" and I'm still on 1.30.0!

Also, 2.x requires JDK8 and my app still has to support JDK6. :-(

Honestly, who uses JDK6 these days. Ridiculous!

**Comment by lukas-krecan** [comment]
Hi, I tried that and unfortunatelly it would not be so easy. Mainly due to the 'ignore' matcher which has completely different behavior than the rest. I recommend you to do the translation as described [here](https://github.com/lukas-krecan/JsonUnit/issues/391#issuecomment-867841637). You can translate the error message too to not confuse the users.

**Comment by k1w1m8** [comment]
I already implemented the translation, I think it's going to be good enough for now. Since I'm stuck on jdk6 atm I wouldn't be able to use a new feature even if you implemented it in 2.x.

So no need to worry.Thanks!
