### ISSUE TITLE
Cannot resolve the library if I use `implementation` in Gradle depedency

### ISSUE THREAD

**Issue by siralam2104** [lukas-krecan/JsonUnit#406]
> Describe which variant of the API are you using (AssertJ, Hamcrest, ...)

AssertJ

I am trying to include the library using `implementation "net.javacrumbs.json-unit:json-unit-assertj:2.27.0"` in Gradle.

If I do this, I cannot resolve the library even at javacrumbs level:
![image](https://user-images.githubusercontent.com/82791939/128333058-bc51cf43-ecfd-4a18-b4f9-c604ed020092.png)

But if I change it to `api "net.javacrumbs.json-unit:json-unit-assertj:2.27.0"`, it works.

But according to my understanding it shouldn't require user to use `api` because we are only interested in the functions that are exposed.

Any idea?

**Comment by lukas-krecan** [comment]
Hi, next time please ask on StackOverflow. If you are using JsonUnit for tests, you should use `testImplementation`
