### ISSUE TITLE
Exception when using org.json.JSONObject object

### ISSUE THREAD

**Issue by dhirenmudgil** [lukas-krecan/JsonUnit#41]
@lukas-krecan @lukas-krecan-gdc 
Getting below exception 

Exception in thread "main" java.lang.IllegalArgumentException: No serializer found for class org.json.JSONObject and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

When using like 

 JSONObject object = new JSONObject();
        object.put("abx","xyz");
        JSONObject object1 = new JSONObject();
        object1.put("qwe","rty");
        CustomMatcher.assertThat(object, JsonMatchers.jsonEquals(object1));

**Comment by lukas-krecan** [comment]
The library is trying to serialize the object to JSON and JSONObject is not supported. It's possible to add the support, but right now I am on vacation. In the meantime you can serialize the object to String or other supported type.



4. 8. 2016 6:44, 6:44, Dhiren Mudgil <notifications@github.com> napsal/a:

**Comment by lukas-krecan** [comment]
Just released version 1.14.0 with org.json support. Enjoy.

**Comment by dhirenmudgil** [comment]
@lukas-krecan Thanks!!!1

**Comment by dhirenmudgil** [comment]
@lukas-krecan Issue is still there when using JSONArray

 public void verifyResponseArray(JSONArray expectedResponseArray, JSONArray actualResponseArray){
        assertThat(expectedResponseArray, JsonMatchers.jsonEquals(actualResponseArray));
    }

It throws the same exception.

**Comment by lukas-krecan** [comment]
Thanks for feedback. Should be fixed in 1.14.1
