### ISSUE TITLE
Please remove logging from library

### ISSUE THREAD

**Issue by reitzmichnicht** [lukas-krecan/JsonUnit#42]
Hi

This is really a great library, but it should not depend on any logging framework.
I now get error messages on console while running unit tests:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

Kind regards,
Michael

**Comment by lukas-krecan** [comment]
SLF4J made optional in 1.15.0

**Comment by reitzmichnicht** [comment]
Thank you
