### ISSUE TITLE
JSON datatype not used correctly 

### ISSUE THREAD

**Issue by m-kay** [lukas-krecan/JsonUnit#453]
When asserting for a specific datatype the library makes some unexpected conversions. JSON strings containing numbers are converted to numbers and assertion with a number does not fail which is wrong in my opinion.

I would have expected the following tests all to pass but only the first two do: 
```java
public class JsonUnitTest {

	@Test
	public void assering_number_value_with_number_should_be_equal(){
		assertThatJson("{\"numberValue\": 1234}").inPath("$.numberValue").isEqualTo(1234);
	}

	@Test
	public void assering_string_value_containing_number_with_number_should_not_be_equal(){
		assertThatJson("{\"stringValue\": \"1234\"}").inPath("$.stringValue").isNotEqualTo(1234);
	}

	@Test
	public void assering_number_value_with_string_should_not_be_equal(){
		assertThatJson("{\"numberValue\": 1234}").inPath("$.numberValue").isNotEqualTo("1234");
	}

	@Test
	public void assering_string_value_containing_number_with_string_should_be_equal(){
		assertThatJson("{\"stringValue\": \"1234\"}").inPath("$.stringValue").isEqualTo("1234");
	}
}
```

In my opinion the actual datatypes should be used as long as no explicit conversion with `.as....()` is done.

**Comment by lukas-krecan** [comment]
Hi, it's documented [here](https://github.com/lukas-krecan/JsonUnit#assertj-integration). Frankly, if I were to write the library again, I would have done it differently, but it's too late to change it now. For simple comparison, I recommend to use `.isString()/.isNumber()` assertion first and then assert the value.
