### ISSUE TITLE
JsonMatchers not doing the correct comparison with DateTime objects 

### ISSUE THREAD

**Issue by lululiu820** [lukas-krecan/JsonUnit#46]
Hi,

I'm using jsonPartEquals from JsonMatchers to do a validation for a DateTime object as a String but the Matcher is not doing the correct comparison. It's breaking down the DateTime object into individual units and as a result, the assertion is failing. Any advice on this issue? Reproducible pasted below.

```
import static org.hamcrest.MatcherAssert.assertThat;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import net.javacrumbs.jsonunit.JsonMatchers;

String my_mock_response = "{\"mock_response\":{\"date\":\"1988-06-22T00:00:00.000Z\"}}";

DateTime date = new DateTime("1988-06-22T00:00:00.000Z", DateTimeZone.UTC);
assertThat(my_mock_response, JsonMatchers.jsonPartEquals("mock_response.date", date));
```

Error message I get:

```
Expected: 1988-06-21T19:00:00.000-05:00 in "mock_response.date"
     but: JSON documents are different:
Different value found in node "mock_response.date". Expected '{"weekyear":1988,"weekOfWeekyear":25,"monthOfYear":6,"yearOfEra":1988,"yearOfCentury":88,"centuryOfEra":19,"millisOfSecond":0,"millisOfDay":68400000,"secondOfMinute":0,"secondOfDay":68400,"minuteOfHour":0,"minuteOfDay":1140,"hourOfDay":19,"year":1988,"dayOfMonth":21,"dayOfWeek":2,"era":1,"dayOfYear":173,"chronology":{"zone":{"fixed":false,"uncachedZone":{"cachable":true,"fixed":false,"id":"America/Chicago"},"id":"America/Chicago"}},"zone":{"fixed":false,"uncachedZone":{"cachable":true,"fixed":false,"id":"America/Chicago"},"id":"America/Chicago"},"millis":582940800000,"afterNow":false,"beforeNow":true,"equalNow":false}', got '"1988-06-22T00:00:00.000Z"'.
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. 

Short answer is, you have to serialize the DateTime object for yourself. For example, if you are using Jackson, you have to convert DateTime to Jackson node and then pass it for comparison.

Detailed explanation follows: In this example you are comparing part of a JSON string and an object. It means that the library has to parse the String, convert it to a node tree and extract the node "mock_response.date". Now it has a node and needs to compare it with an arbitrary object (Joda DateTime in this case). One to do it is to convert DateTime to a Node as well. And this is the place where it fails. JsonUnit supports several JSON libraries and none of the is by default configured to support Joda. Moreover, I do not think it's feasible to do so.

An alternative way would be to try to deserialize the node to DateTime, which would fail for the same reason.
