### ISSUE TITLE
Force to use GSON always

### ISSUE THREAD

**Issue by Ziemowit** [lukas-krecan/JsonUnit#48]
I have bigger project and in its transitive dependencies Jackson2 can be find. But I would like to use Gson in tests. Unfortunately the algorithm is:

        for (int i = 0; i < factories.size(); i++) {
            NodeFactory factory = factories.get(i);
            if (isLastFactory(i) || factory.isPreferredFor(source)) {
                return factory.convertToNode(source, label, lenient);
            }
        }

where the last factory is always Jackson2.
Is there any way to configure JsonUnit to force it to use Gson? Or can it be added?

**Comment by lukas-krecan** [comment]
Thanks for feedback, I can add it. I am just curious why is it a problem, where exactly it fails?

**Comment by lukas-krecan** [comment]
Would something like this be OK? https://github.com/lukas-krecan/JsonUnit/pull/49/files

**Comment by Ziemowit** [comment]
It does not fail :)
The problem is: Gson and Jackson2  converts objects to JSON format in a little bit different way. For example Jackson2 has very irritating "feature" - it cuts off "is" prefix from boolean values. So if in your DTO object you have "boolean isEnabled" then JSON key will be "enabled" by default...

As my REST controllers use Gson for conversion then I would like to have the same converter used in tests.

**Comment by lukas-krecan** [comment]
Just release 1.17.0 where you can specify the library by a system property
