### ISSUE TITLE
JsonPath is not matched when root is array

### ISSUE THREAD

**Issue by afwlehmann** [lukas-krecan/JsonUnit#483]
**Describe the bug**
1. Variant: AssertJ
2. Create a small reproducible example and paste it the the bug report:
    ```
		final String actual = "[ {"
			+ "    \"id\" : 35,"
			+ "    \"name\" : \"A\""
			+ "  }, {"
			+ "    \"id\" : 36,"
			+ "    \"name\" : \"B\""
			+ "  }"
			+ "]";

		assertThatJson(actual)
			.whenIgnoringPaths("$[*].id")
			.isEqualTo("[ {"
				+ "    \"id\" : 1,"
				+ "    \"name\" : \"A\""
				+ "  }, {"
				+ "    \"id\" : 3,"
				+ "    \"name\" : \"B\""
				+ "  }"
				+ "]");
    ```
   The behaviour doesn't change when using `when(path(...), thenIgnore())` or other means of ignoring paths, values, ...
3. Describe expected behavior
    I expected this test to pass but it returns:
    ```
    Different value found in node "[0].id", expected: <1> but was: <35>.
    Different value found in node "[1].id", expected: <3> but was: <36>.
    ```

For comparison, `JsonPath.read(actual, "$[*].id")` returns exactly `[35,36]`.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I will look at it. It seems that `whenIgnoringPaths` has been introduced before support for JsonPath and JsonPath never got implemented there. I will check if it's possible to implement.

**Comment by blackc716** [comment]
Similar problems also exist in `SimplePathMatcher`. When root is array,

```
String expected = "[{\"name\":\"123\",\"age\":2},{\"name\":\"321\",\"age\":5}]";
String actual= "[{\"name\":\"123\",\"age\":5},{\"name\":\"321\",\"age\":8}]";

assertThatJson(expected)
                .whenIgnoringPaths("$..age")
                .isEqualTo(actual);
```
expected return true,actual return false.

**Comment by lukas-krecan** [comment]
> Similar problems also exist in `SimplePathMatcher`. When root is array,
> 
> ```
> String expected = "[{\"name\":\"123\",\"age\":2},{\"name\":\"321\",\"age\":5}]";
> String actual= "[{\"name\":\"123\",\"age\":5},{\"name\":\"321\",\"age\":8}]";
> 
> assertThatJson(expected)
>                 .whenIgnoringPaths("$..age")
>                 .isEqualTo(actual);
> ```
> 
> expected return true,actual return false.

While JsonPath is not supported in `whenIgnoringPaths`, you can use this syntax

```
        assertThatJson(expected)
            .whenIgnoringPaths("[*].age")
            .isEqualTo(actual);
```

**Comment by lukas-krecan** [comment]
Fixed in 3.2.5

**Comment by arshwarsi** [comment]
Hi Lukas , thanks for fixing this. But upgrading to Java 17 is big issue to many people , I am using 2.38.0 because we are still with Java 11. how do we use this fix with Java 11. Any suggestion ?

**Comment by lukas-krecan** [comment]
You can either use the workaround mentioned in the comment above or send a PR to `v2` branch.
