### ISSUE TITLE
AssertionFailedError is missing the actual value for node & inPath methods.

### ISSUE THREAD

**Issue by apozo-copyright** [lukas-krecan/JsonUnit#513]
I expected that methods `node`, `inPath` and similars, when failing, apart from the error itself, they should include the actual value as far as AssertionFailedError supports it. Otherwise the error is very difficult to track.

For example:
`assertThatJson("{\"a\":1}").node("b").isEqualTo(2);`
is only printing
```
org.opentest4j.AssertionFailedError: JSON documents are different:
Missing node in path "b".
``` 

It should print:
```
org.opentest4j.AssertionFailedError: JSON documents are different:
Missing node in path "b".
Actual: {"a":1}
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. That's interesting. If it were `assertThatJson("{\"b\":1}").node("b").isEqualTo(2);` we return 

```
org.opentest4j.AssertionFailedError: JSON documents are different:
Different value found in node "b", 
Expected :2
Actual   :1
```

expected and actual are values of the node `b`.

If `b` missing, what is the actual value? The whole JSON? The parent node? Or nothing? We picked nothing as the node `b` is missing so there is no actual value.

**Comment by apozo-copyright** [comment]
Well, if `b` is missing the assertion message must contain enough information so you can track the error. With the actual implementation, you receive and error, ok, `Missing node in path "b"`, but you can't figure out why is that happening. The argument in `assertThatJson` is usually a variable, not a literal, so the only way you have is debugging or printing the json, which is against purpose of assertion messages. Although the message is raised when the equal assertion happens, what is failing in reality is the location of the node that happen previously. and the message is pointing to that, it has nothing to do with the equality.

So the `actual` value should correspond to the subject JSON not containing the expected node. It should print the immediately previous selected node (in case of nested `node` selections), or at least the whole JSON if that's not possible. I mean:
`assertThatJson("{\"a\":1, \"b\": { \"c\": 2}}").node("b").node("d").isEqualTo(2);`
should print:
````
Missing node in path "b".
Actual: {"b": {"c": 2}}
```
If using the `actual` attribute is conflicting with the specifications, you can think on making the json information just part of the message or use another attribute. But actually is very frustrating when nodes are missing and you can have no idea why.

**Comment by apozo-copyright** [comment]
Hmmm, I had a look to what Spring does with MVC assertions when using `jsonPath` for example. It doesn't neither show the json missing the node, so I may be asking too much then :)
