### ISSUE TITLE
Can't catch any assertions

### ISSUE THREAD

**Issue by hamza-amami** [lukas-krecan/JsonUnit#53]
As I'm comparing tons of Json (rest response and standard files), I want to do the assertions, catch the exception (if exist) and continue my code.
I'm using groovy
Here's my code snippet 
```
try {
	assertJsonEquals(ExpectedResponse, ActualResponse)
}
catch (Exception e) {
	log.info(e)
}
```

The code can't catch the result of the assertions, in fact I want to catch it in a String then parse it (to separate errors found)

Thanks for this amazing library :)

Cheers

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. JsonUnit throws java.lang.AssertionError (as other unit testing library do). AssertionError is NOT subclass of java.lang.Exception.

**Comment by hamza-amami** [comment]
Thanks !
