### ISSUE TITLE
Numerical comparison regression in 2.36.0

### ISSUE THREAD

**Issue by adrogon** [lukas-krecan/JsonUnit#564]
Hello, using `json-unit-fluent`, this was passing in 2.35.0:

```
assertThatJson("{\"a\": 1.0, \"b\": 1.00}")
    .node("a").isEqualTo(1.0)
    .node("b").isEqualTo(1.0);
}
```

but is failing in 2.36.0 with `Different value found in node "b", expected: <1.0> but was: <1.00>.`

It does not look documented, so probably an unintended change?

Thank you :)

**Comment by lukas-krecan** [comment]
```
        assertThatJson("{\"a\": 1.0, \"b\": 1.00}")
            .node("b").isEqualTo("1.00");
```
should work

**Comment by adrogon** [comment]
Thank you for your reply, I'll stick with the `.withTolerance(0.0)` idea instead, and thank you for maintaining the library :)
