### ISSUE TITLE
Ease assertions on content of JSON files

### ISSUE THREAD

**Issue by fstaudt** [lukas-krecan/JsonUnit#567]
**Is your feature request related to a problem? Please describe.**
There is no simple way provided by json-unit-assertj module to assert JSON directly from a JSON file.
It is always required to read the file content before we can use `assertThatJson`.

**Describe the solution you'd like**
Logic to parse a JSON file should be encapsulated in a new class (e.g. JsonFileAssert).

This class should only read the file and delegate JSON assertions on file content to ConfigurableJsonAssert (e.g. `hasContent()`):
``` java
assertThatJsonFile(File("file.json")).hasContent().node("key").isEqualTo("value");
```

**Describe alternatives you've considered**
N/A

**Additional context**
I can provide a PR for this change

**Comment by lukas-krecan** [comment]
Hi, sorry for the late response. I do not think this belongs to the library. It's straigtforward to implement on your side and it would bloat the API unnecesarilly.
