### ISSUE TITLE
Diff message is lost when using jsonEquals with rest-assured

### ISSUE THREAD

**Issue by mmcdermo2** [lukas-krecan/JsonUnit#579]
**Describe the bug**
I'm not 100% sure if this is a rest-assured issue or a JsonUnit issue, but I think it's a JsonUnit issue.  One of the reasons I like this project is because of the useful diff messages when an assertion fails.

- When using this with the hamcrest assertThat, I can see the diff message as expected.
- However, when I use the exact same code with rest assured, the useful diff message is lost, and I just get a generic `"expected x but found y"` message.

**Steps to Reproduce**
```
        given()
                .baseUri("https://reqres.in")
                .basePath("api")
        .when()
                .get("users/1")
        .then()
                .body("", jsonEquals(getResultContent()));
```
Expected Result:
```
Expected: {
  "data": {
    "id": 15,
    "email": "george.bluth@reqres.in",
    "first_name": "George",
    "last_name": "Blunt",
    "avatar": "https://reqres.in/img/faces/1-image.jpg"
  },
  "support": {
    "url": "https://reqres.in/#support-heading",
    "text": "To keep ReqRes free, contributions towards server costs are appreciated!"
  }
}
     but: JSON documents are different:
Different value found in node "data.id", expected <15> but was <1>.
Different value found in node "data.last_name", expected <"Blunt"> but was <"Bluth">.
```

Actual Result
```
Expected: {
  "data": {
    "id": 15,
    "email": "george.bluth@reqres.in",
    "first_name": "George",
    "last_name": "Blunt",
    "avatar": "https://reqres.in/img/faces/1-image.jpg"
  },
  "support": {
    "url": "https://reqres.in/#support-heading",
    "text": "To keep ReqRes free, contributions towards server costs are appreciated!"
  }
}
  Actual: <{data={id=1, email=george.bluth@reqres.in, first_name=George, last_name=Bluth, avatar=https://reqres.in/img/faces/1-image.jpg}, support={url=https://reqres.in/#support-heading, text=To keep ReqRes free, contributions towards server costs are appreciated!}}>
```
- Changing the assertion to use `.body(jsonPartEquals("", getResultContent()));` produces the same result
- I wrote my own custom matcher which is a wrapper for the `jsonEquals` matcher (and saves the diff message), and when I use that matcher I do see the diff message in rest-assured as expected
- Note that in our case, we have some helper methods which read the expected content from an external file (based on the test method name).  Below is the content of that file:
```
{
  "data": {
    "id": 15,
    "email": "george.bluth@reqres.in",
    "first_name": "George",
    "last_name": "Blunt",
    "avatar": "https://reqres.in/img/faces/1-image.jpg"
  },
  "support": {
    "url": "https://reqres.in/#support-heading",
    "text": "To keep ReqRes free, contributions towards server costs are appreciated!"
  }
}
```
**Versions**
Rest Assured 5.2.0
JsonUnit 2.36.0

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Can you please provide more details about your custom matcher, I do not understand how it fixed the issue.

**Comment by deathwaiting** [comment]
For those facing the same problem -and probably using Quarkus-, the issue is from RestAssured, 

The default RestAssured configuration will show an error message generated by RestAssured itself, which compares expected  response vs actual response.
Setting the error description type to `HAMCREST` will make RestAssured use the error message generated by the matchers instead.

So, you have to configure RestAssured error description type to `HAMCREST` instead of the default `REST_ASSURED`.

`RestAssured.config = RestAssuredConfig.config().matcherConfig(matcherConfig().errorDescriptionType(HAMCREST));`
