### ISSUE TITLE
Allow for options after assertion (json-unit-fluent)

### ISSUE THREAD

**Issue by alexfu** [lukas-krecan/JsonUnit#58]
I have a specific use case where I write my assertions like so: `assertThatJson(actual).isEqualTo(expected)`.

However when using the `TREATING_NULL_AS_ABSENT` option in conjunction with the format I use, I end up with a failing test because (assumption here) the option is applied before the assertion. So in order for me to get a passing test, I have to switch it like so: `assertThatJson(expected).when(TREATING_NULL_AS_ABSENT).isEqualTo(actual)`.

Note a huge deal but I do wish to keep my format/ordering consistent across the board if possible.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. The trouble is that the assertion is executed in isEqualTo() method call, and when() is just another method call that happens AFTER the assertion so what you are asking for is not possible. See issue https://github.com/lukas-krecan/JsonUnit/issues/36
