### ISSUE TITLE
Test fails when no dependecy to gson or jackson

### ISSUE THREAD

**Issue by emartynov** [lukas-krecan/JsonUnit#61]
Hi guys,

Our tests are failing because we use Mochi as a json library (https://github.com/square/moshi). As for now we added Gson as test dependency but would be nice to have support for Moshi as well.

Kind Regards,
Eugen

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It should be possible, even though Moshi has some ugly "features" like this https://github.com/square/moshi/issues/192. I already have a commit with the support https://github.com/lukas-krecan/JsonUnit/commit/9ae151324b16cae7e7a12bd52431612f5930b4d1 Will think about it over night and maybe release tomorrow.

**Comment by emartynov** [comment]
It is interesting. I made small comments for the commit.

**Comment by lukas-krecan** [comment]
Released as 1.22.0
