### ISSUE TITLE
Timestamp comparison with tolerance?

### ISSUE THREAD

**Issue by k1w1m8** [lukas-krecan/JsonUnit#63]
I was wondering if there is a way to specify tolerance for timestamp comparisons?

Since my tests run in realtime, I would know the time that should be output to a few seconds, but not an exact value. Currently that forces me to regex the whole timestamp field. 

I was thinking something like {json-unit.timestamp:[period]} could specify that this is a timestamp field and to compare it with a tolerance of [period].

**Comment by lukas-krecan-lt** [comment]
Hi, thanks for feedback. I am quite reluctant to extends {json-unit} macros, I do not want to end-up with a new DSL. I would recommend you to use {json-unit.ignore} and then compare the timestamps separately using hamcrest matchers as described here https://github.com/lukas-krecan/JsonUnit#hamcrests-matchers

**Comment by k1w1m8** [comment]
Hi thanks for replying.

I see what you mean. Hamcrest would be a good match for unit tests.

Unfortunately I am doing high level integration testing using a declarative DSL. Using procedural code such as Hamcrest matchers is a poor fit for my use case.

Is there a SPI for providing your own matching rules using the $ syntax? I was able to something similar in xmlunit using their call back api...

**Comment by lukas-krecan-lt** [comment]
I have been thinking about something like ${json-unit.matcher:matcherName} Where matcherName is a key to some user-provided matcher map. Would something like this solve your problem?

**Comment by k1w1m8** [comment]
Yes I think it would. Seems a nice generalisation if an existing feature as well.

**Comment by lukas-krecan** [comment]
Can you please check that something like this would help you https://github.com/lukas-krecan/JsonUnit/pull/64/files#diff-6c9cdaf0685d47feb195c5cd7da1eb5aR1026

**Comment by k1w1m8** [comment]
It looks like it would. Thanks!

I was thinking that if you pushed it further by adding node type support, you could additionally generalise the existing numeric tolerance support using matchers, which would be quite nice. Maybe something for the future ;-).

**Comment by lukas-krecan-lt** [comment]
Released as 1.23.0. Enjoy

**Comment by k1w1m8** [comment]
Brilliant. Thanks!
