### ISSUE TITLE
floating point numbers comparison regression

### ISSUE THREAD

**Issue by GeorgiPetkov** [lukas-krecan/JsonUnit#638]
Works up to 2.35.0, but doesn't work on 2.36.0 and above. I'm using the AssertJ extension.

```
assertThatJson("1.0E-5").isEqualTo("0.00001");
```

> org.opentest4j.AssertionFailedError: JSON documents are different:
Different value found in node "", 
Expected :0.00001
Actual   :0.000010

Note that the following works (so only actual floating point values are affected):

```
assertThatJson("1E-5").isEqualTo("0.00001");
```

This may seem minor, but the impact is significant because 1.0E-5 is Jackson's default serialization format for such values.

**Comment by lukas-krecan** [comment]
Since 2.38.0 you can specify NumberComparator if you need special handling

**Comment by GeorgiPetkov** [comment]
First of all, thank you very much for your effort on the project and for your swift and helpful response here.

1. If failing to understand the big picture - why on earth is there a separation between integer and floating point when there is no such thing in either JSON or Javascript, there is just **number**?
2. Why wouldn't the default comparison of numbers be numerical?

This is very confusing for new users of the library. I assume this is what happens over tons of gradual changes, trying to keep things backward-compatible and to please everyone. For example, who would even think that there is a comparison of numbers other than numerically?

Another counterintuitive terminology is "exact matching". What is that supposed to mean? As a string? Because in the context of floating point numbers usually this means binary comparison with zero tolerance to differ. And `1.0E-5` and `0.00001` are exactly the same number.

Also, I think you missed the confusing part in the `Expected`/`Actual` output that leads the user towards thinking that the extra trailing `0` is the problem. Maybe it is a problem? It seems wrong that the program ended up with the value `0.000010` seemingly out of nowhere. There might be something more going on here (aside from the misleading output).

**Comment by lukas-krecan** [comment]
Hi, there are two valid points of view.

1. Numbers are compared as numbers 5.0 == 5.00
2. I am writing a unit test and I want to assert that my JSON contains 5.00 and not 5.0

When designing the library, I picked 2. as it seemed more natural to the TDD approach. But some people are proponents of 1. and they find 2. strange and surprising. Imagine I changed the behavior to 1. Then I will get a lot of complaints that the library does not work and that 5.0 is clearly different than 5.00 🤷 . That's why it's clearly documented and why you can pick which version you want.

To make it even more complicated, we are parsing JSON using different libraries, each of them has different quirks when it comes to numeric parsing. That's most likely the source of the trailing 0.

**Comment by GeorgiPetkov** [comment]
OK, I understand that things worked before by "accident" based on the design decisions.

I would however argue about "clearly documented".
1. There is no clear terminology to follow. If we call the non-default comparison "mathematically equal", then what do you call the default? Also, "exact" and "numerical" are very very unsuitable because they do not imply at all to be a different comparison, after all, mathematics is both exact and numerical.
2. The README focuses on the case when types are different. There is no clear explanation of what an "exact match" is.

Playing a bit more with this it appears that  `1.0E-5` as `BigDecimal` is with a scale of 6 (1 for 1.0 + 5 for `E-5`). So I guess "exact match" can be defined as both "mathematically equal" and with the "scale-equal" (or simply "BigDecimal-equal"). This explains why the second example works - it's with a scale of 0 + 5. BTW IMO the decision to have such a stupid `equals` implementation for `BigDecimal` is complete bullshit, it's inconsistent with the `Comparable` interface. And now you inherited this bullshit in your library.

If we accept the above definition of "exact match" we have the following problem - the whole idea of the default behavior to be a very strict comparison is not working as expected. If people what to make the difference between `1.0` and `1.00` they would most likely care about exponential or not format, extra `+` or not, etc. It's clearly not insisting on absolutely the same representation.
