### ISSUE TITLE
Json diff with COMPARING_ONLY_STRUCTURE 

### ISSUE THREAD

**Issue by dozer2** [lukas-krecan/JsonUnit#65]
Hello. Equals 2 json files with COMPARING_ONLY_STRUCTURE not include sub fields. For example:
 {
      "returnDocumentId": 10209,
      "returnDocumentNum": null,
      "returnDocumentType": {
           "returnDocumentTypeId": 1000,
           "name": "test1"
      }
}

and

 {
      "returnDocumentId": 10209,
      "returnDocumentNum": null,
      "returnDocumentType": null
      }

If they was equals with COMPARING_ONLY_STRUCTURE option, result is **succsess**. But expected fail result because  "returnDocumentType" node include 2 fields "returnDocumentTypeId" and "name".

**Comment by lukas-krecan** [comment]
Structural comparison sometimes behaves unexpectedly. Try this instead

        assertJsonEquals(
            "{\n" +
            "\"returnDocumentId\": 100,\n" +
            "\"returnDocumentNum\": null,\n" +
            "\"returnDocumentType\": {\n" +
            "\"returnDocumentTypeId\": 1000,\n" +
            "\"name\": \"test1\"\n" +
            "}\n" +
            "}",
            "{\n" +
            "\"returnDocumentId\": 10209,\n" +
            "\"returnDocumentNum\": null,\n" +
            "\"returnDocumentType\": null\n" +
            "}",
            JsonAssert.when(Option.IGNORING_VALUES));
