### ISSUE TITLE
when abs(a-b) = tolerance,test did not fail

### ISSUE THREAD

**Issue by itlaomo** [lukas-krecan/JsonUnit#656]
using AssertJ
In the document：If you set tolerance to non-zero value, the values are considered equal if **abs(a-b) < tolerance**.

I expected this test to failed，but it pass：
assertThatJson("{\"test\":1.001}").withTolerance(0.001).node("test").isEqualTo(1);

**Comment by lukas-krecan** [comment]
You are right, the documentation was wrong all along. Fixed. Thank you

**Comment by itlaomo** [comment]
Thanks！
But why not fixed the code? it's better

**Comment by lukas-krecan** [comment]
It may break existing tests for many people.
