### ISSUE TITLE
Make it possible to use `withMatcher` for `WebTestClientJsonMatcher`

### ISSUE THREAD

**Issue by hjohn** [lukas-krecan/JsonUnit#657]
The docs read:

    assertThatJson("{\"test\":-1}")
             .withMatcher("positive", greaterThan(valueOf(0)))
             .isEqualTo("{\"test\": \"${json-unit.matches:positive}\"}");

...but I can't seem to apply this when using it in combination with a `WebTestClient`, for example:

        client.get()
            .uri("/someuri")
            .exchange()
            .expectStatus().isOk()
            .expectBody().consumeWith(WebTestClientJsonMatcher.json().isEqualTo("""
                 {
                     "field": "${json.unit.matches:positive}"
                 }
            """);

**Comment by lukas-krecan** [comment]
Will be released shortly as 3.1.0

**Comment by hjohn** [comment]
Thank you, much appreciated, will put it to good use tomorrow!
