### ISSUE TITLE
`gson`: comparing two strings may fail due to lazy number parsing

### ISSUE THREAD

**Issue by liori** [lukas-krecan/JsonUnit#66]
When using `gson` as the JSON parser dependency, the following test fails despite that it shouldn't:

`assertJsonEquals("{\"foo\": 1.0}", "{\"foo\": 1.00}")`

This is because `gson` parser parses numbers lazily: when parsing, it internally stores a string. Then, when serializing, the same string is reused. See the [LazilyParsedNumber](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/LazilyParsedNumber.java) class.

Switching to `moshi` helps.

**Comment by lukas-krecan-lt** [comment]
Number comparison is described here https://github.com/lukas-krecan/JsonUnit#numeric-comparison. By default numbers are compared as literals so 1.0 is different than 1.00. This changes if you set tolerance (even to 0). Moshi is broken so it behaves differently.

**Comment by liori** [comment]
Ah, sorry then. I will keep using `moshi` then, because this is the behavior I consider correct here.
