### ISSUE TITLE
an extension point similar to json-unit.regex 

### ISSUE THREAD

**Issue by k1w1m8** [lukas-krecan/JsonUnit#67]
Hi,

I have a use case where I'd like to capture data during the comparison process, and store it into a variable. One way to do that would be to make an expression like so:

`${json-unit.capture}variable-name`

Adding this directly to json-unit would not make a lot of sense as it is too specific to my needs. 

However, I was thinking possibly this could be accommodated as a generalisation of json-unit.regex, since they both take the same form:

`${json-unit.<name>}<value>`

Would you consider a customisation point that allows the creation of expressions like so?

Thanks

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. To be honest, capturing values does not seem to fit to the library. There are several possible solutions.
1. Use json-path to access the values
2. Use Hamcrest matchers. You can already use Hamcrest matchers with JsonUnit like this `assertThatJson("{\"test\":\"one\"}").node("test").matches(equalTo("one"));` You can use custom capturing matcher (similar to Mockito ArgumentCaptor)

**Comment by k1w1m8** [comment]
Hi, I agree that it doesn't. 😀

It's more the generalisation of the underlying mechanism of json-unit.regex
that I am after.

I have other use cases which require that generalisation as well. It
basically allows a general extension mechanism customise comparison for any
node.

Using matchers is not applicable for me because I am doing integration
testing where the Java API is not accessible - the tests are written by non
developers.

My driver here is that I'm trying to do similar things with json that I
already do for XML using xml-unit. It has a call back API which let me
implement my own version of json-unit.regex for XML.

Would you consider a pull request demonstrating what I am thinking of?

**Comment by lukas-krecan-lt** [comment]
Sure, PRs are always nice. 

It reminds me this feature recently added to JsonUnit https://github.com/lukas-krecan/JsonUnit/commit/a2c26abe8d13580f7cb9a4988db4de7f8a7bb791#diff-6c9cdaf0685d47feb195c5cd7da1eb5aR1021 isn't it what you need?

**Comment by k1w1m8** [comment]
Unfortunately not. I should have anticipated it - fair point. Hamcrest
matchers are good for unit testing but won't accommodate json-unit.regex
style comparison.

**Comment by lukas-krecan-lt** [comment]
OK, I see what you mean. You need additional param. Something like

`assertJsonEquals("{\"test\": \"${json-unit.matches:mymagic}[param]\"}", "{\"test\":1}", JsonAssert.withMatcher("mymagic", myMagicInstance));` That can be done.

**Comment by lukas-krecan-lt** [comment]
No need for PR, I think I know what to do. If you do not mind, I will base it on matchers, will just add a parameter.

**Comment by lukas-krecan** [comment]
What about this? https://github.com/lukas-krecan/JsonUnit/pull/68/commits/c85a70f1be916d8fc6b00adf676f83525c8da477#diff-6c9cdaf0685d47feb195c5cd7da1eb5aR1030

**Comment by k1w1m8** [comment]
Looks good to me.

Extending Matcher fits in elegantly after all 😀.

Thanks!

**Comment by lukas-krecan** [comment]
Released as 1.24.0

**Comment by k1w1m8** [comment]
Awesome. Thanks.

**Comment by k1w1m8** [comment]
Finally got around to actually using this for real, worked perfectly. I can now compare both XML documents  using XML unit, and JSON documents using JsonUnit and, as a side effect of the comparison, capture values into user defined variables using a similar ${} extension mechanism. Brilliant.
