### ISSUE TITLE
Mark JSON-containing paramaters with @Language("JSON")

### ISSUE THREAD

**Issue by foaw** [lukas-krecan/JsonUnit#672]
**Is your feature request related to a problem? Please describe.**
When calling `assertThatJson` and passing a `j.l.String`, it could be specified as such for IntelliJ IDEA. This will enable in-place validation of JSON, enable highlighting, allow opening the fragment in a separate tab, sorting, etc.

**Describe the solution you'd like**
Since the project already uses JetBrains Annotations, it only remains to mark the parameters with [@Language("JSON")](https://javadoc.io/doc/org.jetbrains/annotations/24.0.1/org/intellij/lang/annotations/Language.html).

**Describe alternatives you've considered.**
- One can define their own method with all the necessary overloaded methods on their own and call the delegating utility class instead of `JsonAssertions`.
- It's possible to assign such annotations to parameters locally. However, an `j.l.Object` is expected in the signature, so this isn't an option in the end.

**Additional context**
The parameter type has to be `j.l.String`, so an overloaded method will have to be introduced.

**Comment by lukas-krecan** [comment]
Hi, tha fact that the parameter has to be a String makes it unfeasible. I will not be willing to overload all the methods that accept Object with a String variant just to get better IDE support. The cost is too high for the expected gain. Sorry
