### ISSUE TITLE
Compare with ignore path

### ISSUE THREAD

**Issue by bdjelaili** [lukas-krecan/JsonUnit#69]
Hello,

I have a some hundreds of json scenrio tests and I want to do a json comparison by using ignore paths instead of use "${json-unit.ignore}", Like :

assertThatJson(actualJson)//
.whenIgnore("path1", "path2", ...)//
isEqualTo(expectedJson);

Is it possible to do ?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It sound reasonable and it's possible. Will look at it

**Comment by lukas-krecan** [comment]
Released as 1.25.0

**Comment by bdjelaili** [comment]
Cool, Thank very much :+1:

**Comment by aTan-aka-Xellos** [comment]
@lukas-krecan Hello! Could you please tell, if it possible to ignore path by some kind of regex? 
For example I have 10 nodes and instead of:
whenIgnoringPaths("items[0].ID", "items[1].ID", "items[2].ID", "items[3].ID"...)
write something like: 
whenIgnoringPaths("items[:].ID");
Thank you!

**Comment by lukas-krecan** [comment]
@aTan-aka-Xellos Hi, thanks for feedback. Currently it is not possible.

**Comment by lukas-krecan** [comment]
@aTan-aka-Xellos In 1.28.1 you can use [*]

**Comment by aTan-aka-Xellos** [comment]
@lukas-krecan Thank you!
