### ISSUE TITLE
Is there any way to get text like this .node("status[0].author").getValue();

### ISSUE THREAD

**Issue by prasanna532** [lukas-krecan/JsonUnit#74]

**Comment by prasanna532** [comment]
i seen the method but it is depended on fasterXml but it is there any way without any dependencies.

**Comment by lukas-krecan-lt** [comment]
Hi, there is no such method. You have two options
1. Use json-path https://github.com/json-path/JsonPath
2. Use JsonUnit together with Hamcrest argument captor (matcher)
