### ISSUE TITLE
escape dot in field name for ignoring paths

### ISSUE THREAD

**Issue by zheng-wang** [lukas-krecan/JsonUnit#75]
It seems possible for a JSON field name to contain dot. How to make below assertion pass?

assertJsonEquals(
     "{\"root\":{\"test\":1, \".ignored\": 2}}", 
     "{\"root\":{\"test\":1, \".ignored\": 1}}", 
     JsonAssert.whenIgnoringPaths(`<thePath>`)
);

Should `<thePath>` be something like "root.\\\\.ignored", or some other format?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. This should work

```
        assertJsonEquals(
        "{\"root\":{\"test\":1, \".ignored\": 1}}",
            "{\"root\":{\"test\":1, \".ignored\": 2}}",
        JsonAssert.whenIgnoringPaths("root..ignored")
        );
```

https://github.com/lukas-krecan/JsonUnit/commit/09b2fce7859004948fb6b3062dd37d6f86df89d3

**Comment by zheng-wang** [comment]
Thanks for the quick reply. I also tried more complex name with dots.

        assertJsonEquals(
            "{\"root\":{\"test\":1, \".ignore.d.\": 1}}",
            "{\"root\":{\"test\":1, \".ignore.d.\": 2}}",
            JsonAssert.whenIgnoringPaths("root..ignore.d.")
        );

But as you can see, `root..ignore.d.` seems not very self explaining, as it also works for below JSONs.

        assertJsonEquals(
                "{\"root\":{\"test\":1, \".ignore\": { \"d.\": 1}}}",
                "{\"root\":{\"test\":1, \".ignore\": { \"d.\": 2}}}",
                JsonAssert.whenIgnoringPaths("root..ignore.d.")
        );

I haven't met a problem about this, but have you considered using the same syntax as [JsonPath](https://stackoverflow.com/questions/19726859/jsonpath-junit-escape-character-for-dots/22245630#22245630) to make the path more self explaining?
