### ISSUE TITLE
Consider JsonComparator implementation for Spring Framework 6.2.0

### ISSUE THREAD

**Issue by commonquail** [lukas-krecan/JsonUnit#767]
This is to let JsonUnit know that Spring Framework 6.2.0 is expected to include an `o.s.t.w.s.r.ContentResultMatchers::json` overload that takes an `o.s.t.j.JsonComparator`, a `BiFunction<@Nullable String, @Nullable String, JsonComparison>`, that evaluates a comparison of actual and expected JSON values. JsonUnit may wish to consider this extension mechanism as a complement to its existing Spring Framework integrations.

It looks to me like no official public API of JsonUnit facilitates an ergonomic implementation of `JsonComparator` but that perhaps the internal `Diff` would be the implementation to base an extension on. For now, the following is the plainest implementation I can come up with:

```java
        MockMvcResultMatchers.content().json(read("/foo.json"), (expectedJson, actualJson) -> {
            JsonAssertions.assertThatJson(actualJson).when(Option.IGNORING_EXTRA_FIELDS).isEqualTo(expectedJson);
            return JsonComparison.match();
        });
```

See also

* https://github.com/spring-projects/spring-framework/issues/32791
* https://github.com/spring-projects/spring-boot/issues/15967

**Comment by lukas-krecan** [comment]
Hi, thanks. I will look into that.

**Comment by lukas-krecan** [comment]
https://docs.spring.io/spring-framework/docs/6.2.0-SNAPSHOT/javadoc-api/org/springframework/test/json/JsonComparator.html

**Comment by lukas-krecan** [comment]
Basic support is here https://github.com/lukas-krecan/JsonUnit/pull/772/files

**Comment by commonquail** [comment]
That's quite elegant

**Comment by lukas-krecan** [comment]
It will be part of 4.x release once Spring 6.2 is out
