### ISSUE TITLE
Jackson2NodeFactory does not handle BinaryNode

### ISSUE THREAD

**Issue by Yekut** [lukas-krecan/JsonUnit#78]
It seems `Jackson2NodeFactory` does not handle [BinaryNode](https://fasterxml.github.io/jackson-databind/javadoc/2.4/com/fasterxml/jackson/databind/node/BinaryNode.html), which means when JsonUnit (at least `jsonEquals`) encounters one, it'll throw instead of do a proper operation which is a bit confusing/unhelpful.

I discovered this while trying to do a comparison between two byte arrays - I can probably make a small reproducible fragment if this is deemed worth fixing.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It's definitely worth fixing and a small test would be appreciated.

**Comment by lukas-krecan** [comment]
Released as 1.25.1
