### ISSUE TITLE
Json structure comparison

### ISSUE THREAD

**Issue by nlenoire** [lukas-krecan/JsonUnit#79]
In some previous releases of the library, there was a {{JsonFluentAssert.hasSameStructureAs}} method that is now deprecated without any true replacement. This method was really useful for testing that a Json payload has expected property names.

Is there any chance to see this method to make a come back?...

Thanks for your answer, and for your great lib (which would be even greater with hasSameStructureAs).

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. hasSameStructureAs has been deprecated since it was unpredictable in some edge cases. You can try option IGNORE_VALUES which should do more-or-less the same https://github.com/lukas-krecan/JsonUnit#options

**Comment by nlenoire** [comment]
I already tried IGNORING_VALUES, but this doesn't seem to work for embedded objects.
E.g.

    json1 =  {
       "anObject": {
           "prop": "value"      
       }
    }

    json2 =  {
       "anObject": ""
    }

    assertThatJson(json1).when(IGNORING_VALUES).isEqual(json2) => fails

**Comment by lukas-krecan** [comment]
I see your point, but this behavior is exactly why the method is deprecated. json1 and json2 do not have the same structure and the method says they do. Some users were quite surprised by this behavior. That being said, I am thinking about implementing IGNORING_MISSING_FIELDS https://github.com/lukas-krecan/JsonUnit/issues/80 which would bring back the behavior of hasSameStructureAs, this time in a less surprising way.

**Comment by nlenoire** [comment]
This could work. I close this issue.
