### ISSUE TITLE
It would be cool to have a IGNORING_MISSING_FIELDS

### ISSUE THREAD

**Issue by BrianBohe** [lukas-krecan/JsonUnit#80]
https://github.com/lukas-krecan/JsonUnit/blob/73f597a8197b6a127f11bbaf1235f41825e06d95/json-unit-core/src/main/java/net/javacrumbs/jsonunit/core/internal/Diff.java#L178

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. It would be easy to implement but it would have interesting consequences. Would an empty document always pass (all fields are missing)?

**Comment by BrianBohe** [comment]
I don't see the problem if you don't want to see it. The case is something like this:

You want to **_assertJsonEquals_**
Origin ['a':1, 'b':2, 'c':null, 'somethingThatAlwaysExistsButIDontCare':null]
Dest:  ['a':1, 'b':2, 'c':null]

Your test could just need to check a few keys in a map. Not all of them. In this case I only care about values of keys {'a','b','c'}

**Comment by lukas-krecan** [comment]
I understand, but the unfortunate side effect is that 
    `assertThatJson("{}")
    .when(IGNORING_MISSING_FIELDS)
    .isEqualTo("{'a':1, 'b':2, 'c':null]}");`

passes as well. So if you code breaks in such a way that it completely stops generating JSON, your tests will pass. It might be unpleasant surprise. Anyway, I plan to add the feature but I will somehow mark it as unsafe.

**Comment by lukas-krecan** [comment]
I will also add ${json-unit.any} placeholder which might be more suitable in such case.

**Comment by lukas-krecan** [comment]
In the meantime you can use ${json-unit.ignore} placeholder

**Comment by lukas-krecan** [comment]
Hi, sorry, but I have been thinking about it and I apparently still do not understand the use-case. Why can't you use this?
```
assertThatJson("{\"test\":{\"a\":1, \"b\":2, \"c\":3}}") //actual
   .when(IGNORING_EXTRA_FIELDS)
   .isEqualTo("{\"test\":{\"b\":2}}"); //expected
```
thanks for explanation

**Comment by lukas-krecan** [comment]
In do not understand the use-case - closing
