### ISSUE TITLE
New GPG Key has no Metadata

### ISSUE THREAD

**Issue by DennisRippinger** [lukas-krecan/JsonUnit#815]
For the lulz, I have a plugin running in some of our pipelines that checks the validity of GPG Keys. With version 2.40.0 of JsonUnit, the GPG Key changed from [0x3F999BB69041CF17E73BB1CEC038787776A19D18](https://keyserver.ubuntu.com/pks/lookup?search=0x3F999BB69041CF17E73BB1CEC038787776A19D18&fingerprint=on&op=index) (which has regular Metadata) to [0xEED6202038849B47FEEAD1EC9266326161C26F29](https://keys.openpgp.org/search?q=0xEED6202038849B47FEEAD1EC9266326161C26F29) which has no metadata to do a sanity check. Is this intended?

**Comment by lukas-krecan** [comment]
Hi, it's possible. I will check next week. Thanks for reporting

**Comment by lukas-krecan** [comment]
Just released 3.5.0, the key should be better now

**Comment by pzygielo** [comment]
Can't find the key 0xEED6202038849B47FEEAD1EC9266326161C26F29 in none of: hkps://pgp.surfnet.nl, hkps://keyserver.ubuntu.com, hkps://keys.openpgp.org, hkps://pgpkeys.eu.

Could you revisit this and publish key used to sign `net/javacrumbs/json-unit/json-unit-core/2.40.1/json-unit-core-2.40.1.jar`, please?

**Comment by lukas-krecan** [comment]
Hi, @pzygielo that's strange, Maven central does not allow releasing artifacts that are signed by an unpublished key. I have just republished the key

**Comment by pzygielo** [comment]
> I have just republished the key

Perfect! I have imported that key now.
Thank you.
