### ISSUE TITLE
Implement more verbal assertion error messages

### ISSUE THREAD

**Issue by xp-vit** [lukas-krecan/JsonUnit#84]
Library assertion error messages need to be more verbal. They need to tell more about the issue. For example when assertion "isStringEqualTo" fails the following result get printed:
`java.lang.AssertionError: Node "error.message" is not equal to "Query parameter 'startDateTime' is required`

The better message will be:
`java.lang.AssertionError: Node "error.message" is not equal to "Query parameter 'startDateTime' is required"`

`java.lang.AssertionError: 
Expecting:
 <"Query parameter 'startDateTime2' is required">
to be equal:
 <"Query parameter 'startDateTime' is required">`

let me know your opinion and I might work on implementation of this feature.

**Comment by lukas-krecan** [comment]
Hi thanks for feedback. If I understand it correctly, you are missing the actual value from the error message?

**Comment by xp-vit** [comment]
@lukas-krecan true. I think it will be really useful to have it.

**Comment by lukas-krecan** [comment]
Makes sense, I have been looking at it and it's seems that one has to extends some JUnit classes in order to have nicely formatted error in IntelliJ. Will look at it some more.

**Comment by lukas-krecan** [comment]
Sorry, I have been mistaken, not need to extend any class, will fix it

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit/pull/85
