### ISSUE TITLE
Support for Assertj's InstanceOfAssertFactory

### ISSUE THREAD

**Issue by etrandafir93** [lukas-krecan/JsonUnit#853]
I've noticed a few deprecated methods with the reason `InstanceOfAssertFactory is not supported with JsonUnit` and I was wondering if this class would worth adding or if you had issues with it in the past.

As far as I'm aware, implementing the `InstanceOfAssertFactory` is pretty straight-forward. I've taken the freedom to fork the project and sketch out a possible solution: here is [my commit](https://github.com/etrandafir93/JsonUnit/commit/d250bfaacc621bc55f1baa89f74219a57d0702bd#diff-a44b989dd035468d4e38b290bed51a9d850605e7bfd9822d9a39e1b0fab7b34bR5).

Apart from enabling users to use the currently deprecated methods, this also provides a nice way of navigating from the Assertj world to JsonUnit, for example:

```java
assertThat("{}")
  .asInstanceOf(JsonUnitAssertFactory.JSON)
  .isObject()
  .isEmpty();
```

Here is a more realistic example:

```java
record DummyResponse(String trackingId, String json) {}
DummyResponse resp = new DummyResponse("abcd-0001", "{ \"foo\": \"bar\" }");

assertThat(resp)
  .hasFieldOrPropertyWithValue("trackingId", "abcd-0001")  //<- Assertj API
  .extracting("json").asInstanceOf(JsonUnitAssertFactory.JSON)
  .isObject().containsEntry("foo", "bar"); // <- JsonUnit API
```

If this looks interesting, I can raise a PR. Let me know what you think

**Comment by lukas-krecan** [comment]
Hi, thanks for suggestion. I am preparing version 4 to be released after Spring release at the end of this month. And I had something similar, so it was just a metter of [a few lines](https://github.com/lukas-krecan/JsonUnit/pull/786/commits/b7cef541fcc76158e228f121895e346f2730f1a0#diff-642a52fede8473f98c5a7b25f34c6bd68f33160cf22733127f7f7f13f3cb2fc6R2244), Is this what you had in mind? I am struggling a bit with naming, do you have any suggestions about how to name the methods?

**Comment by etrandafir93** [comment]
yes, something like that :) I see - naming is tricky here.

I don't know really.. As an alternative maybe you can put the methods into different static inner classes and keep the method name itself very simple (maybe `SpringMvcToJsonUnit.json()` and `AssertJToJsonUnit.json()`?)

This will be more readable, especially if they are not used together and we can use static imports:
```
.bodyJson().convertTo(json())
// or
.extracting("jsonField").asInstanceOf(json())
```

**Comment by lukas-krecan** [comment]
Will be part of v4 release. Thanks
