### ISSUE TITLE
Matching problem when both `IGNORING_ARRAY_ORDER` and `IGNORING_EXTRA_ARRAY_ITEMS` enabled.

### ISSUE THREAD

**Issue by jiefangxuanyan** [lukas-krecan/JsonUnit#86]
`assertJsonEquals("[[2],[1]]", "[[1,2],[2]]", when(IGNORING_ARRAY_ORDER, IGNORING_EXTRA_ARRAY_ITEMS));`
I think this should be passing.
[1] matches [1,2] and [2] matches [2].
But actually [2] matches [1,2] and the assertion fails.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback, it is indeed a bug but not one easy to fix. Will take a look at it in next few weeks.

**Comment by lukas-krecan** [comment]
Fix released in 1.27.0

**Comment by jiefangxuanyan** [comment]
Thanks😊
