### ISSUE TITLE
Enhance "isAbsent" assertion message

### ISSUE THREAD

**Issue by xp-vit** [lukas-krecan/JsonUnit#88]
Let's say we have code:

`JsonFluentAssert.assertThatJson(responseBody)
                .node("error").isAbsent();`

Currently when isAbsent assertion fails we got message:

`Node "error" is present.`

I think it will be make it more verbose. Let's say:
`Node "error" is present and equal to "Server is broken. Sorry.".`

**Comment by lukas-krecan** [comment]
Hi, thanks fro feedback. For this release I have been unifying error messages in #85 so I will unify isAbsent and isPresent messages as well. Please check https://github.com/lukas-krecan/JsonUnit/pull/89/files if it makes sense to you.

**Comment by lukas-krecan** [comment]
Released as 1.26.0

**Comment by xp-vit** [comment]
Great, Thanks!
