### ISSUE TITLE
Use of alternative org.json dependency 

### ISSUE THREAD

**Issue by kovax** [lukas-krecan/JsonUnit#91]
I am using this org.json library for my projects:

https://mvnrepository.com/artifact/org.json/json/20171018

It would be good to know if I could use it instead of the default org.json dependency.

**Comment by kovax** [comment]
Actually my test was successful, but it be reassuring if this library officially supported.

**Comment by lukas-krecan** [comment]
Well, there there is no time to test all possible versions of all supported libraries, but I would say it should be ok. Usually if the library authors break backward compatibility it fails quite fast (on missing method, different signature etc.).
