### ISSUE TITLE
Unable to set multiple custom matchers

### ISSUE THREAD

**Issue by luke84** [lukas-krecan/JsonUnit#95]
With reference to custom matchers example in the readme (below), I was wondering if it would be possible to add support for >1 custom matchers? The Matchers class is package private and uses a Map to store the matchers, however I am only able to set a single matcher per configuration via the withMatcher method on the Configuration instance. 
Also, the getMatcher method on the Configuration instance somewhat gives the impression that multiple matchers can be set, even though only a single matcher can be set via the withMatcher method.

```
Matcher<?> divisionMatcher = new DivisionMatcher();
 assertJsonEquals(
     "{test: '${json-unit.matches:isDivisibleBy}3'}", 
     "{\"test\":5}", 
     JsonAssert.withMatcher("isDivisibleBy", divisionMatcher)
 );
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. This works for me, am I missing something?

```
        Matcher<?> divisionMatcher = new DivisionMatcher();
        Matcher<?> emptyMatcher = empty();

        assertJsonEquals(
            "{test: '${json-unit.matches:isDivisibleBy}3', x: '${json-unit.matches:isEmpty}'}",
            "{\"test\":6, \"x\": []}",
            JsonAssert
                .withMatcher("isDivisibleBy", divisionMatcher)
                .withMatcher("isEmpty", emptyMatcher)
        );
```

**Comment by luke84** [comment]
Cheers, yes that will do it. Thanks.
