### ISSUE TITLE
Allow configuring the underlying library using a known (property?) file on classpath

### ISSUE THREAD

**Issue by akshaydewan** [lukas-krecan/JsonUnit#96]
We have a situation where there are several json libraries on the classpath (gson, jackson, json.org).

To be able to run tests in the IDE, the current implementation requires us to setup a system property in each test. This is undesirable and error-prone.

We are thinking if it makes sense to add a property file at known location in the classpath to be able to specify the underlying json library. That way, we wouldn't need to set the system property in every test:

```properties
# net/javacrumbs/jsonunit/core/converter.properties
json-unit.libraries=gson
```
The [Converter#createDefaultConverter](https://github.com/lukas-krecan/JsonUnit/blob/ff7ca82a550db9b50f60274a891cd926b6a28fa6/json-unit-core/src/main/java/net/javacrumbs/jsonunit/core/internal/Converter.java#L58-L72) method can then lookup the property file, and if it exists, read the property from the file.

If there is a better way of doing this, we're happy to take a different approach and submit a PR.

**Comment by mprins** [comment]
You could easily create an abstract superclass that you inherit from in all your cases to do this when using eg junit with a @BeforeClass

**Comment by akshaydewan** [comment]
That definitely can be done, though programmers would have the overhead of remembering to use the superclass. It seems like a small thing, but we're working on a large, legacy codebase, so anything that involves developers remembering things becomes more error prone.

**Comment by lukas-krecan** [comment]
Hi, I see your point but there really is lot of options how you can set the system property so I would prefer to not add such feature.
