### ISSUE TITLE
IGNORING_VALUES Option doesn't ignore null values

### ISSUE THREAD

**Issue by vanilsonsantos** [lukas-krecan/JsonUnit#97]
Hi, I'm trying to compare only the json structure ignoring null values but the option IGNORING_VALUES is considering the null values, Is it a bug or I need to combine with another option?

**Comment by lukas-krecan-lt** [comment]
Hi, could you provide an example please?

**Comment by vanilsonsantos** [comment]
Hi,

I would like to compare:
assertJsonEquals("{\"test\":1}", "{\"test\": null }", when(IGNORING_VALUES));

I'm able to do it using the COMPARING_ONLY_STRUCTURE option, but I'm little bit worried once this option is deprecated.

**Comment by lukas-krecan-lt** [comment]
The failure is intentional since `null` is not an `int`. You can try to use 

`assertJsonEquals("{"test":"${json-unit.ignore}"}", "{"test": null }")`

**Comment by vanilsonsantos** [comment]
I see,

the problem is I'm getting the expected json structure dynamically and I needed to change a lot of values on the fly =/ , but thanks for the help =)

**Comment by lukas-krecan-lt** [comment]
Well, you can use COMPARING_ONLY_STRUCTURE, it's deprecated mainly because it returns surprising results like 

assertJsonEquals("{"test":{"a": 1}}", "{"test": null }"

but maybe it's something you need. Will think about it.

**Comment by vanilsonsantos** [comment]
Thanks a lot and congratulations for this great library.
