### ISSUE TITLE
Custom matchers do not work properly when } is in the value

### ISSUE THREAD

**Issue by k1w1m8** [lukas-krecan/JsonUnit#98]
Hi,

When using a custom matcher with a json value which contains `}`, the regex used internally to parse the matcher name from the value gets confused and the custom matcher is no longer selected properly.

The regex in question is from the `Diff` class.

`private static final Pattern MATCHER_PLACEHOLDER_PATTERN = Pattern.compile("\\$\\{json-unit.matches:(.+)\\}(.*)");`

The `(.+)` is where the issue is. 

I was able to temporarily work around the issue by using a reflection hack to update the pattern to 

`"\\$\\{json-unit.matches:([a-zA-Z]+)\\}(.*)"`

Not sure that is the best way to do it but it worked enough for me ;-).

**Comment by lukas-krecan-lt** [comment]
Hi, thanks, can you please send an example of failing test?

**Comment by k1w1m8** [comment]
Sure, here is an example. It fails like so

`java.lang.AssertionError: JSON documents are different:
Matcher "embedded}{"x" : "y"" not found.`

If you change the pattern as per the commented lines, it works.

`
public class EmbeddedJsonTest {

    @Test
    public void testSomething() throws Exception {

        // updatePrivateStaticField(Diff.class, "MATCHER_PLACEHOLDER_PATTERN",
        //    Pattern.compile("\\$\\{json-unit.matches:([a-zA-Z]+)\\}(.*)"));

        String expected =
            "{ \"o\" : \"${json-unit.matches:embedded}{\\\"x\\\" : \\\"y\\\"}\" }";
        String actual =
            "{ \"o\" : \"{\\\"x\\\" : \\\"y\\\"}\" }";

        JsonAssert.assertJsonEquals(expected, actual,
            JsonAssert.withMatcher("embedded", new EmbeddedJSONMatcher()));

    }

    private static void updatePrivateStaticField(Class<Diff> clazz, String fieldName, Object value) throws Exception {
        Field field = clazz.getDeclaredField(fieldName);
        field.setAccessible(true);
        Field modifiersField = Field.class.getDeclaredField("modifiers");
        modifiersField.setAccessible(true);
        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
        field.set(null, value);
    }


    static class EmbeddedJSONMatcher extends BaseMatcher<Object> implements ParametrizedMatcher {

        private String expected;

        public void setParameter(String parameter) {
            this.expected = parameter;
        }

        public boolean matches(Object actual) {
            try {
                JsonAssert.assertJsonEquals(expected, actual);
                return true;
            } catch (java.lang.AssertionError error) {
                // Hmm. Should we record the mismatch result here for use later?
                return false;
            }
        }

        public void describeTo(Description description) {
            description
                .appendText("embeddedJson(")
                .appendValue(expected)
                .appendText(")");
        }

        @Override
        public void describeMismatch(Object actual, Description description) {

            java.lang.AssertionError error = null;
            try {
                JsonAssert.assertJsonEquals(expected, actual);
            } catch (java.lang.AssertionError e) {
                error = e;
            }
            description
                .appendValue("Embedded JSON: Actual ")
                .appendValue(actual)
                .appendText(" doesn't match expected ")
                .appendValue(expected)
                .appendText(" due to " + error.getMessage());
        }

    }
}
`

**Comment by lukas-krecan** [comment]
Released as 1.28.2

**Comment by k1w1m8** [comment]
Wow - that was quick.

Thanks!
