### ISSUE TITLE
Ignoring presence of a particular property

### ISSUE THREAD

**Issue by SatyamJ** [lukas-krecan/JsonUnit#99]
Is there a way to ignore a specific or list of properties?

**Comment by lukas-krecan** [comment]
See this section of documentation https://github.com/lukas-krecan/JsonUnit#ignoring-values

**Comment by SatyamJ** [comment]
@lukas-krecan as far I understand that ignores values. My question is about ignoring keys. Is there a way of doing that?

**Comment by SatyamJ** [comment]
I have a 
Base document:
`{
"fname" : "xyz",
"lname": "abc"
}`

Target document (which needs to be compared against the base document):
`{
 "fname": "xyz"
}`
I want this comparison to pass. Currently json unit requires target document to have 2nd property "lname" with a liberty of holding any value with ignoring-values feature.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit#ignoring-paths

**Comment by SatyamJ** [comment]
Thanks that worked!
Great library!
